export const frameworks = {
   "Ideon Flow": [
    { title: "Nome do Projeto", hint: "Escolha um nome claro e memorável.", span: 6 },
{ title: "Objetivo Principal", hint: "O que você quer alcançar ao final do projeto?", span: 6 },
{ title: "Área de Atuação", hint: "Ex.: tecnologia, educação, saúde, entretenimento.", span: 6 },
{ title: "Problema Central", hint: "Qual dor ou necessidade o projeto resolve?", span: 6 },
{ title: "Público-Alvo", hint: "Quem será beneficiado ou impactado?", span: 6 },
{ title: "Nível de Experiência", hint: "Iniciante, intermediário ou avançado.", span: 6 },
{ title: "Recursos Disponíveis", hint: "Tempo, equipe, ferramentas e habilidades já disponíveis.", span: 6 },
{ title: "Orçamento Inicial", hint: "Quanto você está disposto a investir no início?", span: 6 },
{ title: "Prazo Desejado", hint: "Tempo total estimado para concluir o projeto.", span: 6 },
{ title: "Critério de Sucesso", hint: "Como você saberá que o projeto atingiu o objetivo?", span: 6 },
{ title: "Descrição Geral", hint: "Um breve resumo do projeto e sua visão.", span: 12 }

  ],
  "Lean Canvas Expandido": [
    { title: "Nome do Projeto", hint: "Um nome claro e memorável.", span: 6 },
    { title: "Problema", hint: "Que problema real você resolve?", span: 6 },
    { title: "Solução", hint: "Como sua solução endereça o problema?", span: 6 },
    { title: "Proposta de Valor", hint: "O que torna sua solução única?", span: 6 },
    { title: "Público/Segmentos", hint: "Quem são os usuários ou clientes?", span: 6 },
    { title: "Canais", hint: "Como você chega ao público?", span: 6 },
    { title: "MVP", hint: "Qual é o mínimo para testar valor?", span: 6 },
    { title: "Validação", hint: "Como você medirá o sucesso inicial?", span: 6 },
    { title: "OKRs", hint: "Objetivos e resultados-chave.", span: 6 },
    { title: "Custos", hint: "Principais custos.", span: 6 },
    { title: "Receitas", hint: "Fontes de receita.", span: 6 },
    { title: "Descrição", hint:"Breve descrição do projeto.", span:12}
  ],
  "Proposta de Valor (VPC)": [
    { title: "Cliente-Alvo", hint: "Quem é o cliente e contexto?", span: 6 },
    { title: "Tarefas do Cliente", hint: "O que tentam realizar?", span: 6 },
    { title: "Dores", hint: "Obstáculos e frustrações.", span: 6 },
    { title: "Ganhos", hint: "Resultados desejados.", span: 6 },
    { title: "Produtos/Serviços", hint: "O que você oferece?", span: 6 },
    { title: "Aliviadores de Dor", hint: "Como reduz as dores?", span: 6 },
    { title: "Criadores de Ganho", hint: "Como gera ganhos?", span: 6 }
  ],
  "Mini Roadmap de Projeto": [
    { title: "Objetivo", hint: "Resultado principal do período.", span: 12 },
    { title: "Marcos", hint: "Etapas chave.", span: 6 },
    { title: "Tarefas", hint: "Lista priorizada.", span: 6 },
    { title: "Riscos/Dependências", hint: "O que pode impactar.", span: 12 }
  ],
  "Pitch Rápido": [
    { title: "Problema", hint: "", span: 6 },
    { title: "Solução", hint: "", span: 6 },
    { title: "Diferencial", hint: "", span: 6 },
    { title: "Mercado", hint: "", span: 6 },
    { title: "Tração/Provas", hint: "", span: 6 },
    { title: "Call-to-Action", hint: "", span: 6 },
  ],
  "Canvas do IdeiaHub (custom)": [
    { title: "Visão", hint: "Onde queremos chegar?", span: 12 },
    { title: "Usuários", hint: "", span: 6 },
    { title: "Solução", hint: "", span: 6 },
    { title: "Métricas-Chave", hint: "", span: 6 },
    { title: "Experimentos", hint: "", span: 6 },
    { title: "Roadmap", hint: "", span: 12 },
  ],
  "SWOT Simplificado": [
    { title: "Forças", hint: "", span: 6 },
    { title: "Fraquezas", hint: "", span: 6 },
    { title: "Oportunidades", hint: "", span: 6 },
    { title: "Ameaças", hint: "", span: 6 },
  ],
  "Product Management Canvas": [
    { title: "Problema", hint: "", span: 6 },
    { title: "Público", hint: "", span: 6 },
    { title: "Proposta de Valor", hint: "", span: 6 },
    { title: "Métricas", hint: "", span: 6 },
    { title: "Canais", hint: "", span: 6 },
    { title: "Monetização", hint: "", span: 6 },
  ],
  "Roadmap Trimestral": [
    { title: "Q Objetivos", hint: "", span: 12 },
    { title: "Em Andamento", hint: "", span: 6 },
    { title: "Próximo", hint: "", span: 6 },
    { title: "Riscos", hint: "", span: 12 },
  ],
  "Go-To-Market (GTM) Lite": [
    { title: "Segmento-Alvo", hint: "", span: 6 },
    { title: "Proposta de Valor", hint: "", span: 6 },
    { title: "Canais", hint: "", span: 6 },
    { title: "Mensagem", hint: "", span: 6 },
    { title: "Táticas Iniciais", hint: "", span: 12 },
  ],
  "Plano de Entrevista com Clientes": [
    { title: "Objetivo da Entrevista", hint: "", span: 12 },
    { title: "Perfil dos Entrevistados", hint: "", span: 6 },
    { title: "Roteiro de Perguntas", hint: "", span: 6 },
    { title: "Notas", hint: "", span: 12 },
  ],
  "Mapa da Jornada do Cliente (Lite)": [
    { title: "Estágios", hint: "Descoberta > Consideração > Decisão > Retenção", span: 12 },
    { title: "Ações do Cliente", hint: "", span: 12 },
    { title: "Pontos de Dor", hint: "", span: 6 },
    { title: "Oportunidades", hint: "", span: 6 },
  ],
  "Brief de Funcionalidade": [
    { title: "Resumo", hint: "", span: 12 },
    { title: "Problema", hint: "", span: 6 },
    { title: "Solução Proposta", hint: "", span: 6 },
    { title: "Critérios de Aceite", hint: "", span: 12 },
  ],
  "Estratégia de Precificação": [
    { title: "Proposta de Valor", hint: "", span: 12 },
    { title: "Segmentos/Planos", hint: "", span: 6 },
    { title: "Preço Inicial", hint: "", span: 6 },
    { title: "Teste & Validação", hint: "", span: 12 },
  ],
};

export const templates = {
  "Clube de Horta Urbana": {
    "Nome do Projeto": "HortaClub",
    "Problema": "Moradores urbanos têm pouco acesso a espaços verdes e alimentos frescos.",
    "Solução": "Clubes de hortas compartilhadas em prédios e bairros com kits e mentorias.",
    "Público/Segmentos": "Moradores de apartamentos, síndicos, escolas.",
    "Canais": "Parcerias com condomínios, redes sociais locais, feiras de bairro.",
    "MVP": "Instalação de 1 horta piloto em um prédio e encontros semanais.",
    "Validação": "Número de participantes ativos e safra colhida em 60 dias.",
    "OKRs": "O: Validar interesse; KR1: 30 participantes; KR2: 2 colheitas/mês",
    "Forças": "Interesse crescente por sustentabilidade, comunidade engajada.",
    "Fraquezas": "Dependência de espaço físico, sazonalidade das colheitas.",
    "Oportunidades": "Parcerias com escolas e ONGs, expansão para mais prédios.",
    "Ameaças": "Concorrência de hortas comunitárias, regulamentações locais." ,
  },
  "Correção Colaborativa de Redações": {
    "Problema": "Estudantes carecem de feedback rápido e qualificado.",
    "Solução": "Plataforma com correção por pares e monitores.",
    "Público": "Alunos de ensino médio, cursinhos.",
    "Canais": "Parcerias com escolas, influenciadores educacionais.",
    "MVP": "Turma piloto com 50 alunos e 2 correções semanais.", 
    "Validação": "Taxa de aprovação em simulados 20% maior que média.",
    "OKRs": "O: Melhorar notas; KR1: 80% dos alunos com notas acima de 7; KR2: 90% de feedback positivo.",
    "Forças": "Alta demanda por correção de redações, comunidade escolar engajada.",
    "Fraquezas": "Dependência de voluntários, necessidade de treinamento.", 
    "Oportunidades": "Expansão para outras disciplinas, parcerias com cursinhos.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    },
  "Feira Online do Bairro": {
    "Problema": "Produtores locais não alcançam compradores digitais.",
    "Solução": "Marketplace hiperlocal com logística colaborativa.",
    "Canais": "Grupos de WhatsApp, associações de bairro.",
    "MVP": "Landing + catálogo simples + entregas em um dia fixo.",
    "Validação": "50 pedidos no primeiro mês e 20% de recompra.",
    "OKRs": "O: Criar comunidade; KR1: 100 usuários ativos no primeiro mês; KR2: 50 pedidos semanais.",
    "Forças": "Apoio à economia local, interesse por produtos frescos.",
    "Fraquezas": "Logística complexa, dependência de tecnologia.",
    "Oportunidades": "Parcerias com feiras e produtores, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes marketplaces, regulamentações locais.",
  
  },
  "App de Roteiros de Caminhadas Locais": {
    "Problema": "Falta de rotas seguras e interessantes nas redondezas.",
    "Solução": "App com roteiros curados e gamificação.",
    "MVP": "Mapa com 5 rotas e sistema de badges.",
    "Validação": "100 downloads e 50 rotas completadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de caminhantes; KR1: 200 downloads; KR2: 100 rotas completadas.",
    "Forças": "Crescimento do interesse por atividades ao ar livre, comunidade local engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com academias e lojas de esportes, expansão",
    "Ameaças": "Concorrência de apps de caminhada, mudanças climáticas.",

  },
  "Plataforma de Troca de Habilidades": {
    "Problema": "Pessoas querem aprender sem alto custo.",
    "Solução": "Créditos por aula ensinada para aprender outra habilidade.",
    "Público/Segmentos": "Estudantes, profissionais em transição de carreira.",
    "Canais": "Universidades, grupos de interesse, redes sociais.",
    "MVP": "Landing page + 10 aulas disponíveis + sistema de créditos.",
    "Validação": "50 usuários ativos e 100 aulas trocadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de aprendizado; KR1: 200 usuários ativos; KR2: 500 aulas trocadas.",
    "Forças": "Alta demanda por aprendizado acessível, comunidade engajada.", 
    "Fraquezas": "Dependência de voluntários, necessidade de curadoria.",
    "Oportunidades": "Parcerias com escolas e universidades, expansão para outras cidades.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    
  },
  "Loja Virtual de Produtos Artesanais Locais": {
    "Problema": "Artesãos têm pouca presença online.",
    "Solução": "Loja compartilhada com vitrine e logística simples.",
    "Proposta de Valor":"Teste",
    "Público/Segmentos":"Luiz",
    "Canais":"Canal",
    "MVP":"Produto",
    "Validação":"Valido",
    "OKRs":"kit",
    "Custos":"preço",
    "Receitas":"R$",
    "Forças": "Apoio à economia local, interesse por produtos únicos.",
    "Fraquezas": "Dependência de tecnologia, logística complexa.",
    "Oportunidades": "Parcerias com feiras e eventos locais, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes marketplaces, regulamentações locais.",
    
  },
  "Painel de Indicadores para Pequenos Negócios": {
    "Problema": "Empreendedores não têm visão consolidada de indicadores.",
    "Solução": "Dashboard simples integrado a planilhas.",
    "Público/Segmentos": "Pequenos empresários, freelancers.",
    "Canais": "Grupos de empreendedores, redes sociais.", 
    "MVP": "Dashboard com 5 indicadores principais e integração com Google Sheets.",
    "Validação": "10 negócios ativos e 50 indicadores visualizados no primeiro mês.",
    "OKRs": "O: Melhorar gestão; KR1: 20 negócios ativos; KR2: 100 indicadores visualizados.",
    "Forças": "Alta demanda por gestão simples, comunidade empreendedora engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de treinamento.",
    "Oportunidades": "Parcerias com associações de empreendedores, expansão para outras cidades.",
    "Ameaças": "Concorrência de ferramentas consolidadas, resistência a mudanças",
  },
  "Rede de Apoio a Mães Empreendedoras": {
    "Problema": "Falta de networking e suporte flexível.",
    "Solução": "Comunidade, mentorias e marketplace.",
    "Público/Segmentos": "Mães empreendedoras, freelancers.",
    "Canais": "Grupos de mães, redes sociais, eventos locais.",
    "MVP": "Grupo no WhatsApp + 1 evento mensal + marketplace simples.",
    "Validação": "50 mães ativas e 10 negócios no marketplace no primeiro mês.",
    "OKRs": "O: Criar comunidade de apoio; KR1: 100 mães ativas; KR2: 20 negócios no marketplace.",
    "Forças": "Alta demanda por suporte, comunidade engajada.", 
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria.",
    "Oportunidades": "Parcerias com escolas e ONGs, expansão para outras cidades.",
    "Ameaças": "Concorrência de grupos consolidados, resistência a mudanças.",  

    
  },
  "Projeto Educacional Gamificado": {
    "Problema": "Baixa motivação em estudos remotos.",
    "Solução": "Metas, missões e recompensas.",
    "Público/Segmentos": "Estudantes do ensino médio, professores.",
    "Canais": "Escolas, redes sociais, influenciadores educacionais.",
    "MVP": "Plataforma com 5 missões e sistema de recompensas.",
    "Validação": "50 alunos ativos e 20% de aumento na participação em 30 dias.",
    "OKRs": "O: Aumentar engajamento; KR1: 100 alunos ativos; KR2: 50% de participação em missões.",
    "Forças": "Interesse crescente por gamificação, comunidade escolar engajada.",  
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com escolas e ONGs, expansão para outras disciplinas.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    "Proposta de Valor": "Gamificação do aprendizado para aumentar engajamento.", 
    "Segmentos/Planos": "Estudantes do ensino médio, professores.",
    "Preço Inicial": "R$ 29,90/mês por aluno.",
    "Teste & Validação": "Taxa de participação em missões e feedback dos alunos.",


  },
  "Central de Ofertas Comunitárias": {
    "Problema": "Ofertas locais se perdem em vários canais.",
    "Solução": "Hub único de promoções do bairro.",
    "Público/Segmentos": "Moradores locais, pequenos comerciantes.",
    "Canais": "Grupos de WhatsApp, redes sociais locais, associações de bairro.",
    "MVP": "Landing page com 10 ofertas e grupo de WhatsApp.",
    "Validação": "100 usuários ativos e 50 ofertas resgatadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de consumo local; KR1: 200 usuários ativos; KR2: 100 ofertas resgatadas.",
    "Forças": "Apoio à economia local, interesse por ofertas exclusivas.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria.",
    "Oportunidades": "Parcerias com comerciantes locais, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes plataformas, regulamentações locais.",

  },
};
