export const frameworks = {
  "Lean Canvas Expandido": [
    { title: "Nome do Projeto", hint: "Um nome claro e memorável.", span: 6 },
    { title: "Problema", hint: "Que problema real você resolve?", span: 6 },
    { title: "Solução", hint: "Como sua solução endereça o problema?", span: 6 },
    { title: "Proposta de Valor", hint: "O que torna sua solução única?", span: 6 },
    { title: "Público/Segmentos", hint: "Quem são os usuários ou clientes?", span: 6 },
    { title: "Canais", hint: "Como você chega ao público?", span: 6 },
    { title: "MVP", hint: "Qual é o mínimo para testar valor?", span: 6 },
    { title: "Validação", hint: "Como você medirá o sucesso inicial?", span: 6 },
    { title: "OKRs", hint: "Objetivos e resultados-chave.", span: 6 },
    { title: "Custos", hint: "Principais custos.", span: 6 },
    { title: "Receitas", hint: "Fontes de receita.", span: 6 }
  ],
  "Proposta de Valor (VPC)": [
    { title: "Cliente-Alvo", hint: "Quem é o cliente e contexto?", span: 6 },
    { title: "Tarefas do Cliente", hint: "O que tentam realizar?", span: 6 },
    { title: "Dores", hint: "Obstáculos e frustrações.", span: 6 },
    { title: "Ganhos", hint: "Resultados desejados.", span: 6 },
    { title: "Produtos/Serviços", hint: "O que você oferece?", span: 6 },
    { title: "Aliviadores de Dor", hint: "Como reduz as dores?", span: 6 },
    { title: "Criadores de Ganho", hint: "Como gera ganhos?", span: 6 }
  ],
  "Mini Roadmap de Projeto": [
    { title: "Objetivo", hint: "Resultado principal do período.", span: 12 },
    { title: "Marcos", hint: "Etapas chave.", span: 6 },
    { title: "Tarefas", hint: "Lista priorizada.", span: 6 },
    { title: "Riscos/Dependências", hint: "O que pode impactar.", span: 12 }
  ],
  "Pitch Rápido": [
    { title: "Problema", span: 6 },
    { title: "Solução", span: 6 },
    { title: "Diferencial", span: 6 },
    { title: "Mercado", span: 6 },
    { title: "Tração/Provas", span: 6 },
    { title: "Call-to-Action", span: 6 },
  ],
  "Canvas do IdeiaHub (custom)": [
    { title: "Visão", hint: "Onde queremos chegar?", span: 12 },
    { title: "Usuários", span: 6 },
    { title: "Solução", span: 6 },
    { title: "Métricas-Chave", span: 6 },
    { title: "Experimentos", span: 6 },
    { title: "Roadmap", span: 12 },
  ],
  "SWOT Simplificado": [
    { title: "Forças", span: 6 },
    { title: "Fraquezas", span: 6 },
    { title: "Oportunidades", span: 6 },
    { title: "Ameaças", span: 6 },
  ],
  "OKRs de Projeto": [
    { title: "Objetivo", hint: "Inspira e direciona.", span: 12 },
    { title: "KR1", hint: "Mensurável e claro.", span: 4 },
    { title: "KR2", hint: "Mensurável e claro.", span: 4 },
    { title: "KR3", hint: "Mensurável e claro.", span: 4 },
    { title: "Iniciativas", hint: "O que faremos para alcançar.", span: 12 },
  ],
  "Product Management Canvas": [
    { title: "Problema", span: 6 },
    { title: "Público", span: 6 },
    { title: "Proposta de Valor", span: 6 },
    { title: "Métricas", span: 6 },
    { title: "Canais", span: 6 },
    { title: "Monetização", span: 6 },
  ],
  "Roadmap Trimestral": [
    { title: "Q Objetivos", span: 12 },
    { title: "Em Andamento", span: 6 },
    { title: "Próximo", span: 6 },
    { title: "Riscos", span: 12 },
  ],
  "BRD — Requisitos de Negócio": [
    { title: "Contexto", span: 12 },
    { title: "Stakeholders", span: 6 },
    { title: "Objetivos de Negócio", span: 6 },
    { title: "Escopo", span: 12 },
    { title: "Critérios de Sucesso", span: 12 },
  ],
  "PRD — Requisitos de Produto": [
    { title: "Visão do Produto", span: 12 },
    { title: "Usuários & Personas", span: 6 },
    { title: "Funcionalidades", span: 6 },
    { title: "Requisitos Funcionais", span: 6 },
    { title: "Requisitos Não-Funcionais", span: 6 },
    { title: "Métricas", span: 6 },
  ],
  "Cartão de Experimento Lean": [
    { title: "Hipótese", span: 12 },
    { title: "Métrica Sucesso", span: 6 },
    { title: "Plano de Teste", span: 6 },
    { title: "Resultado", span: 12 },
    { title: "Aprendizados", span: 12 },
  ],
  "Go-To-Market (GTM) Lite": [
    { title: "Segmento-Alvo", span: 6 },
    { title: "Proposta de Valor", span: 6 },
    { title: "Canais", span: 6 },
    { title: "Mensagem", span: 6 },
    { title: "Táticas Iniciais", span: 12 },
  ],
  "Plano de Entrevista com Clientes": [
    { title: "Objetivo da Entrevista", span: 12 },
    { title: "Perfil dos Entrevistados", span: 6 },
    { title: "Roteiro de Perguntas", span: 6 },
    { title: "Notas", span: 12 },
  ],
  "Mapa da Jornada do Cliente (Lite)": [
    { title: "Estágios", hint: "Descoberta > Consideração > Decisão > Retenção", span: 12 },
    { title: "Ações do Cliente", span: 12 },
    { title: "Pontos de Dor", span: 6 },
    { title: "Oportunidades", span: 6 },
  ],
  "Brief de Funcionalidade": [
    { title: "Resumo", span: 12 },
    { title: "Problema", span: 6 },
    { title: "Solução Proposta", span: 6 },
    { title: "Critérios de Aceite", span: 12 },
  ],
  "Estratégia de Precificação": [
    { title: "Proposta de Valor", span: 12 },
    { title: "Segmentos/Planos", span: 6 },
    { title: "Preço Inicial", span: 6 },
    { title: "Teste & Validação", span: 12 },
  ],
};