export const frameworks = {
   "Ideon Flow": [
    { title: "Nome do Projeto", hint: "Escolha um nome claro e memorável.", span: 6 },
{ title: "Objetivo Principal", hint: "O que você quer alcançar ao final do projeto?", span: 6 },
{ title: "Área de Atuação", hint: "Ex.: tecnologia, educação, saúde, entretenimento.", span: 6 },
{ title: "Problema Central", hint: "Qual dor ou necessidade o projeto resolve?", span: 6 },
{ title: "Público-Alvo", hint: "Quem será beneficiado ou impactado?", span: 6 },
{ title: "Nível de Experiência", hint: "Iniciante, intermediário ou avançado.", span: 6 },
{ title: "Recursos Disponíveis", hint: "Tempo, equipe, ferramentas e habilidades já disponíveis.", span: 6 },
{ title: "Orçamento Inicial", hint: "Quanto você está disposto a investir no início?", span: 6 },
{ title: "Prazo Desejado", hint: "Tempo total estimado para concluir o projeto.", span: 6 },
{ title: "Critério de Sucesso", hint: "Como você saberá que o projeto atingiu o objetivo?", span: 6 },
{ title: "Descrição Geral", hint: "Um breve resumo do projeto e sua visão.", span: 12 }

  ],
  "Lean Canvas Expandido": [
    { title: "Nome do Projeto", hint: "Um nome claro e memorável.", span: 6 },
    { title: "Problema", hint: "Que problema real você resolve?", span: 6 },
    { title: "Solução", hint: "Como sua solução endereça o problema?", span: 6 },
    { title: "Proposta de Valor", hint: "O que torna sua solução única?", span: 6 },
    { title: "Público/Segmentos", hint: "Quem são os usuários ou clientes?", span: 6 },
    { title: "Canais", hint: "Como você chega ao público?", span: 6 },
    { title: "MVP", hint: "Qual é o mínimo para testar valor?", span: 6 },
    { title: "Validação", hint: "Como você medirá o sucesso inicial?", span: 6 },
    { title: "OKRs", hint: "Objetivos e resultados-chave.", span: 6 },
    { title: "Custos", hint: "Principais custos.", span: 6 },
    { title: "Receitas", hint: "Fontes de receita.", span: 6 },
    { title: "Descrição", hint:"Breve descrição do projeto.", span:12}
  ],
  "Business Model Canvas (BMC)": [
    { title: "Segmentos de Clientes", hint: "Quem são seus clientes?", span: 6 },
    { title: "Proposta de Valor", hint: "Que valor você oferece?", span: 6 },
    { title: "Canais", hint: "Como você alcança seus clientes?", span: 6 },
    { title: "Relacionamento com Clientes", hint: "Como você interage com os clientes?", span: 6 },
    { title: "Fontes de Receita", hint: "Como você ganha dinheiro?", span: 6 },
    { title: "Recursos Principais", hint: "Quais ativos são essenciais?", span: 6 },
    { title: "Atividades-Chave", hint: "Quais ações são cruciais?", span: 6 },
    { title: "Parcerias Principais", hint: "Quem são seus parceiros?", span: 6 },
    { title: "Estrutura de Custos", hint: "Quais são os custos mais importantes?", span: 6 }
  ],
  "Lean Startup": [
    { title: "Visão", hint: "Qual é a visão de longo prazo?", span: 12 },
    { title: "Problema", hint: "Qual problema você está resolvendo?", span: 6 },
    { title: "Solução", hint: "Qual é a solução proposta?", span: 6 },
    { title: "Métricas-Chave", hint: "Quais métricas indicarão sucesso?", span: 6 },
    { title: "Canais", hint: "Como você alcançará seus clientes?", span: 6 },
    { title: "Estrutura de Custos", hint: "Quais são os custos principais?", span: 6 },
    { title: "Fontes de Receita", hint: "Como você gerará receita?", span: 6 },
    { title: "MVP", hint: "Qual é o produto mínimo viável?", span: 12 },
    { title: "Feedback & Aprendizado", hint: "Como você coletará feedback?", span: 12 }
  ],
  "Kanban": [
    { title: "Backlog", hint: "Tarefas pendentes.", span: 4 },
    { title: "Em Progresso", hint: "Tarefas em andamento.", span: 4 },
    { title: "Em Revisão", hint: "Tarefas para revisão ou teste.", span: 4 },
    { title: "Concluído", hint: "Tarefas finalizadas.", span: 4 },
    { title: "Bloqueado", hint: "Tarefas com impedimentos.", span: 4 },
    { title: "Prioridade", hint: "Tarefas de alta prioridade.", span: 4 }
  ],
  "Proposta de Valor (VPC)": [
    { title: "Cliente-Alvo", hint: "Quem é o cliente e contexto?", span: 6 },
    { title: "Tarefas do Cliente", hint: "O que tentam realizar?", span: 6 },
    { title: "Dores", hint: "Obstáculos e frustrações.", span: 6 },
    { title: "Ganhos", hint: "Resultados desejados.", span: 6 },
    { title: "Produtos/Serviços", hint: "O que você oferece?", span: 6 },
    { title: "Aliviadores de Dor", hint: "Como reduz as dores?", span: 6 },
    { title: "Criadores de Ganho", hint: "Como gera ganhos?", span: 6 }
  ],
  "Mini Roadmap de Projeto": [
    { title: "Objetivo", hint: "Resultado principal do período.", span: 12 },
    { title: "Marcos", hint: "Etapas chave.", span: 6 },
    { title: "Tarefas", hint: "Lista priorizada.", span: 6 },
    { title: "Riscos/Dependências", hint: "O que pode impactar.", span: 12 }
  ],
  "Pitch Rápido": [
    { title: "Problema", hint: "", span: 6 },
    { title: "Solução", hint: "", span: 6 },
    { title: "Diferencial", hint: "", span: 6 },
    { title: "Mercado", hint: "", span: 6 },
    { title: "Tração/Provas", hint: "", span: 6 },
    { title: "Call-to-Action", hint: "", span: 6 },
  ],
  "Canvas do IdeiaHub (custom)": [
    { title: "Visão", hint: "Onde queremos chegar?", span: 12 },
    { title: "Usuários", hint: "", span: 6 },
    { title: "Solução", hint: "", span: 6 },
    { title: "Métricas-Chave", hint: "", span: 6 },
    { title: "Experimentos", hint: "", span: 6 },
    { title: "Roadmap", hint: "", span: 12 },
  ],
  "SWOT Simplificado": [
    { title: "Forças", hint: "", span: 6 },
    { title: "Fraquezas", hint: "", span: 6 },
    { title: "Oportunidades", hint: "", span: 6 },
    { title: "Ameaças", hint: "", span: 6 },
  ],
  "Product Management Canvas": [
    { title: "Problema", hint: "", span: 6 },
    { title: "Público", hint: "", span: 6 },
    { title: "Proposta de Valor", hint: "", span: 6 },
    { title: "Métricas", hint: "", span: 6 },
    { title: "Canais", hint: "", span: 6 },
    { title: "Monetização", hint: "", span: 6 },
  ],
  "Roadmap Trimestral": [
    { title: "Q Objetivos", hint: "", span: 12 },
    { title: "Em Andamento", hint: "", span: 6 },
    { title: "Próximo", hint: "", span: 6 },
    { title: "Riscos", hint: "", span: 12 },
  ],
  "Go-To-Market (GTM) Lite": [
    { title: "Segmento-Alvo", hint: "", span: 6 },
    { title: "Proposta de Valor", hint: "", span: 6 },
    { title: "Canais", hint: "", span: 6 },
    { title: "Mensagem", hint: "", span: 6 },
    { title: "Táticas Iniciais", hint: "", span: 12 },
  ],
  "Plano de Entrevista com Clientes": [
    { title: "Objetivo da Entrevista", hint: "", span: 12 },
    { title: "Perfil dos Entrevistados", hint: "", span: 6 },
    { title: "Roteiro de Perguntas", hint: "", span: 6 },
    { title: "Notas", hint: "", span: 12 },
  ],
  "Mapa da Jornada do Cliente (Lite)": [
    { title: "Estágios", hint: "Descoberta > Consideração > Decisão > Retenção", span: 12 },
    { title: "Ações do Cliente", hint: "", span: 12 },
    { title: "Pontos de Dor", hint: "", span: 6 },
    { title: "Oportunidades", hint: "", span: 6 },
  ],
  "Brief de Funcionalidade": [
    { title: "Resumo", hint: "", span: 12 },
    { title: "Problema", hint: "", span: 6 },
    { title: "Solução Proposta", hint: "", span: 6 },
    { title: "Critérios de Aceite", hint: "", span: 12 },
  ],
  "Estratégia de Precificação": [
    { title: "Proposta de Valor", hint: "", span: 12 },
    { title: "Segmentos/Planos", hint: "", span: 6 },
    { title: "Preço Inicial", hint: "", span: 6 },
    { title: "Teste & Validação", hint: "", span: 12 },
  ],
};

export const templates = {
  "Clube de Horta Urbana": {
    
  "Ameaças": "Concorrência de hortas comunitárias, regulamentações locais.",
  "Área de Atuação": "Sustentabilidade, alimentação saudável, comunidade.",
  "Canais": "Parcerias com condomínios, redes sociais locais, feiras de bairro.",
  "Critérios de Aceite": "Horta instalada, 30 participantes ativos, 2 colheitas mensais.",
  "Critério de Sucesso": "Horta instalada, 30 participantes ativos, 2 colheitas mensais.",
  "Custos": "R$ 500 para instalação inicial, R$ 200 mensais de manutenção.",
  "Descrição Geral": "HortaClub conecta moradores urbanos com hortas compartilhadas, promovendo alimentação saudável e sustentabilidade.",
  "Forças": "Interesse crescente por sustentabilidade, comunidade engajada.",
  "Fraquezas": "Dependência de espaço físico, sazonalidade das colheitas.",
  "MVP": "Instalação de 1 horta piloto em um prédio e encontros semanais.",
  "Nome do Projeto": "HortaClub",
  "Nível de Experiência": "Iniciante",
  "Objetivo Principal": "Conectar moradores urbanos com hortas compartilhadas.",
  "OKRs": "O: Validar interesse; KR1: 30 participantes; KR2: 2 colheitas/mês",
  "Oportunidades": "Parcerias com escolas e ONGs, expansão para mais prédios.",
  "Orçamento Inicial": "R$ 500 para instalação inicial, R$ 200 mensais de manutenção.",
  "Prazo Desejado": "3 meses para validação inicial.",
  "Preço Inicial": "R$ 49,90/mês por participante.",
  "Problema": "Moradores urbanos têm pouco acesso a espaços verdes e alimentos frescos.",
  "Problema Central": "Moradores urbanos têm pouco acesso a espaços verdes e alimentos frescos.",
  "Público/Segmentos": "Moradores de apartamentos, síndicos, escolas.",
  "Público-Alvo": "Moradores urbanos, síndicos de prédios, escolas.",
  "Receitas": "R$ 49,90/mês por participante, R$ 200 de patrocínios locais.",
  "Recursos Disponíveis": "Espaço em prédios, voluntários, ferramentas de jardinagem.",
  "Resumo": "HortaClub conecta moradores urbanos com hortas compartilhadas, promovendo alimentação saudável e sustentabilidade.",
  "Solução": "Clubes de hortas compartilhadas em prédios e bairros com kits e mentorias.",
  "Solução Proposta": "Criar hortas urbanas compartilhadas com kits de cultivo e mentorias.",
  "Validação": "Número de participantes ativos e safra colhida em 60 dias."
  },

  "Sistema de Votação Autônomo para Condomínios":
    {
  "nomeDoProjeto": "VotaçãoCondo",
  "Objetivo Principal": "Um aplicativo descentralizado que permite que moradores de condomínios votem em pautas importantes de forma transparente e imutável, sem a necessidade de assembleias presenciais.",
  "Problema": "Assembleias de condomínio são burocráticas, com baixa participação e resultados que geram desconfiança.",
  "Solução": "Uma plataforma baseada em DApps (Aplicativos Descentralizados) que permite a votação online, auditável e imutável.",
  "Solução Proposta": "Criar um sistema de votação para condomínios usando tecnologia blockchain, garantindo transparência e segurança.",
  "Público/Segmentos": "Moradores de condomínios residenciais e comerciais, síndicos, administradoras de condomínios.",
  "Canais": "Parcerias com administradoras de condomínios, associações de síndicos, marketing digital focado em grupos de moradores.",
  "MVP": "Um aplicativo com registro de moradores e votação para uma única pauta, como a eleição do síndico.",
  "Validação": "Implementação em 5 condomínios-piloto, com 80% de participação nas votações em 3 meses.",
  "Critérios de Aceite": "Sistema de votação funcional, relatório de auditoria, 80% de participação nos condomínios-piloto.",
  "OKRs": "O: Aumentar a participação em assembleias; KR1: 80% de participação em 3 meses; KR2: 100% de transparência em pautas votadas.",
  "Forças": "Transparência via blockchain, facilidade de uso, aumento da participação dos moradores.",
  "Fraquezas": "Custo inicial de desenvolvimento, curva de aprendizado para alguns usuários, necessidade de regulamentação.",
  "Oportunidades": "Expansão para assembleias de associações e escolas, integrações com sistemas de gestão de condomínios.",
  "Ameaças": "Desafios de segurança digital, resistência de síndicos a novas tecnologias, regulamentações governamentais.",
  "Resumo": "VotaçãoCondo é um DApp para votações de condomínio, focado em aumentar a participação e garantir a transparência de forma segura.",
  "Área de Atuação": "Propriedade, finanças, comunidade, tecnologia.",
  "Nível de Experiência": "Intermediário a Avançado",
  "Recursos Disponíveis": "Desenvolvedores de blockchain, especialistas em UX/UI, síndicos parceiros.",
  "Prazo Desejado": "6 meses para um MVP funcional e validado.",
  "Critério de Sucesso": "Implementação bem-sucedida em 5 condomínios-piloto e feedback positivo dos moradores."
},
  
  "Correção Colaborativa de Redações": {
    "Problema": "Estudantes carecem de feedback rápido e qualificado.",
    "Solução": "Plataforma com correção por pares e monitores.",
    "Público": "Alunos de ensino médio, cursinhos.",
    "Canais": "Parcerias com escolas, influenciadores educacionais.",
    "MVP": "Turma piloto com 50 alunos e 2 correções semanais.", 
    "Validação": "Taxa de aprovação em simulados 20% maior que média.",
    "OKRs": "O: Melhorar notas; KR1: 80% dos alunos com notas acima de 7; KR2: 90% de feedback positivo.",
    "Forças": "Alta demanda por correção de redações, comunidade escolar engajada.",
    "Fraquezas": "Dependência de voluntários, necessidade de treinamento.", 
    "Oportunidades": "Expansão para outras disciplinas, parcerias com cursinhos.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    },
  "Feira Online do Bairro": {
    "Problema": "Produtores locais não alcançam compradores digitais.",
    "Solução": "Marketplace hiperlocal com logística colaborativa.",
    "Canais": "Grupos de WhatsApp, associações de bairro.",
    "MVP": "Landing + catálogo simples + entregas em um dia fixo.",
    "Validação": "50 pedidos no primeiro mês e 20% de recompra.",
    "OKRs": "O: Criar comunidade; KR1: 100 usuários ativos no primeiro mês; KR2: 50 pedidos semanais.",
    "Forças": "Apoio à economia local, interesse por produtos frescos.",
    "Fraquezas": "Logística complexa, dependência de tecnologia.",
    "Oportunidades": "Parcerias com feiras e produtores, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes marketplaces, regulamentações locais.",
  
  },
  "App de Roteiros de Caminhadas Locais": {
    "Problema": "Falta de rotas seguras e interessantes nas redondezas.",
    "Solução": "App com roteiros curados e gamificação.",
    "MVP": "Mapa com 5 rotas e sistema de badges.",
    "Validação": "100 downloads e 50 rotas completadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de caminhantes; KR1: 200 downloads; KR2: 100 rotas completadas.",
    "Forças": "Crescimento do interesse por atividades ao ar livre, comunidade local engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com academias e lojas de esportes, expansão",
    "Ameaças": "Concorrência de apps de caminhada, mudanças climáticas.",

  },
  "Plataforma de Troca de Habilidades": {
    "Problema": "Pessoas querem aprender sem alto custo.",
    "Solução": "Créditos por aula ensinada para aprender outra habilidade.",
    "Público/Segmentos": "Estudantes, profissionais em transição de carreira.",
    "Canais": "Universidades, grupos de interesse, redes sociais.",
    "MVP": "Landing page + 10 aulas disponíveis + sistema de créditos.",
    "Validação": "50 usuários ativos e 100 aulas trocadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de aprendizado; KR1: 200 usuários ativos; KR2: 500 aulas trocadas.",
    "Forças": "Alta demanda por aprendizado acessível, comunidade engajada.", 
    "Fraquezas": "Dependência de voluntários, necessidade de curadoria.",
    "Oportunidades": "Parcerias com escolas e universidades, expansão para outras cidades.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    
  },
  "Loja Virtual de Produtos Artesanais Locais": {
    "Problema": "Artesãos têm pouca presença online.",
    "Solução": "Loja compartilhada com vitrine e logística simples.",
    "Proposta de Valor":"Teste",
    "Público/Segmentos":"Luiz",
    "Canais":"Canal",
    "MVP":"Produto",
    "Validação":"Valido",
    "OKRs":"kit",
    "Custos":"preço",
    "Receitas":"R$",
    "Forças": "Apoio à economia local, interesse por produtos únicos.",
    "Fraquezas": "Dependência de tecnologia, logística complexa.",
    "Oportunidades": "Parcerias com feiras e eventos locais, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes marketplaces, regulamentações locais.",
    
  },
  "Painel de Indicadores para Pequenos Negócios": {
    "Problema": "Empreendedores não têm visão consolidada de indicadores.",
    "Solução": "Dashboard simples integrado a planilhas.",
    "Público/Segmentos": "Pequenos empresários, freelancers.",
    "Canais": "Grupos de empreendedores, redes sociais.", 
    "MVP": "Dashboard com 5 indicadores principais e integração com Google Sheets.",
    "Validação": "10 negócios ativos e 50 indicadores visualizados no primeiro mês.",
    "OKRs": "O: Melhorar gestão; KR1: 20 negócios ativos; KR2: 100 indicadores visualizados.",
    "Forças": "Alta demanda por gestão simples, comunidade empreendedora engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de treinamento.",
    "Oportunidades": "Parcerias com associações de empreendedores, expansão para outras cidades.",
    "Ameaças": "Concorrência de ferramentas consolidadas, resistência a mudanças",
  },
  "Rede de Apoio a Mães Empreendedoras": {
    "Problema": "Falta de networking e suporte flexível.",
    "Solução": "Comunidade, mentorias e marketplace.",
    "Público/Segmentos": "Mães empreendedoras, freelancers.",
    "Canais": "Grupos de mães, redes sociais, eventos locais.",
    "MVP": "Grupo no WhatsApp + 1 evento mensal + marketplace simples.",
    "Validação": "50 mães ativas e 10 negócios no marketplace no primeiro mês.",
    "OKRs": "O: Criar comunidade de apoio; KR1: 100 mães ativas; KR2: 20 negócios no marketplace.",
    "Forças": "Alta demanda por suporte, comunidade engajada.", 
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria.",
    "Oportunidades": "Parcerias com escolas e ONGs, expansão para outras cidades.",
    "Ameaças": "Concorrência de grupos consolidados, resistência a mudanças.",  

    
  },
  "Projeto Educacional Gamificado": {
    "Problema": "Baixa motivação em estudos remotos.",
    "Solução": "Metas, missões e recompensas.",
    "Público/Segmentos": "Estudantes do ensino médio, professores.",
    "Canais": "Escolas, redes sociais, influenciadores educacionais.",
    "MVP": "Plataforma com 5 missões e sistema de recompensas.",
    "Validação": "50 alunos ativos e 20% de aumento na participação em 30 dias.",
    "OKRs": "O: Aumentar engajamento; KR1: 100 alunos ativos; KR2: 50% de participação em missões.",
    "Forças": "Interesse crescente por gamificação, comunidade escolar engajada.",  
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com escolas e ONGs, expansão para outras disciplinas.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    "Proposta de Valor": "Gamificação do aprendizado para aumentar engajamento.", 
    "Segmentos/Planos": "Estudantes do ensino médio, professores.",
    "Preço Inicial": "R$ 29,90/mês por aluno.",
    "Teste & Validação": "Taxa de participação em missões e feedback dos alunos.",


  },
  "AgTech - Mercado de Permacultura Urbana": {
  "nomeDoProjeto": "EcoMercado Urbano",
  "Objetivo Principal": " Uma plataforma que conecta produtores de alimentos em pequena escala (hortas em telhados, pequenos quintais) com restaurantes locais e consumidores dispostos a pagar por produtos ultra-locais.",  
  "Problema": "Moradores urbanos têm dificuldade em encontrar alimentos frescos e sustentáveis, enquanto pequenos produtores não têm um canal de vendas direto.", 
  "Solução": "Uma plataforma online para que produtores de permacultura urbana vendam seus produtos, e consumidores assinem cestas semanais de alimentos locais.",  
  "Solução Proposta": "Desenvolver um marketplace que conecte produtores e consumidores de permacultura urbana, com um sistema de assinaturas e entrega direta.", 
  "Público/Segmentos": "Consumidores conscientes, moradores urbanos, restaurantes locais, pequenos produtores urbanos.",  
  "Canais": "Feiras de bairro, redes sociais (grupos de alimentação saudável), parcerias com cafeterias e restaurantes.", 
  "MVP": "Um site simples com um sistema de assinatura para 10 produtores e 50 clientes iniciais em um bairro específico.", 
  "Validação": "Acompanhamento da frequência de pedidos semanais, feedback dos clientes e crescimento do número de produtores inscritos.",  
  "Critérios de Aceite": "50 assinaturas ativas, 10 produtores registrados e uma taxa de satisfação de 90% dos clientes.",  
  "OKRs": "O: Validar o modelo de negócio; KR1: 50 assinaturas ativas em 3 meses; KR2: 10 produtores na plataforma.", 
  "Forças": "Crescente demanda por alimentos locais e orgânicos, forte apelo comunitário.",
  "Fraquezas": "Escalabilidade limitada por espaço físico, desafios logísticos de entrega, dependência de um pequeno número de produtores.",  
  "Oportunidades": "Expansão para outros produtos sustentáveis, parcerias com restaurantes e escolas, educação sobre permacultura.",  
  "Ameaças": "Concorrência de grandes redes de supermercados, regulamentações locais sobre venda de alimentos, sazonalidade dos produtos.",  
  "Resumo": "EcoMercado Urbano é um marketplace que facilita a conexão entre produtores de alimentos em permacultura urbana e consumidores locais, promovendo um sistema alimentar mais justo e sustentável.",  
  "Área de Atuação": "Alimentação, sustentabilidade, comunidade, tecnologia.",  
  "Nível de Experiência": "Intermediário",  
  "Recursos Disponíveis": "Plataforma online, rede de produtores urbanos, lideranças comunitárias.",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",  
  "Preço Inicial": "Taxa de assinatura para consumidores, comissão sobre as vendas para os produtores.",
  "Receitas": "Comissão sobre vendas, taxa de assinatura, patrocínios de marcas sustentáveis.",
  "Recursos Disponíveis": "Plataforma online, rede de produtores urbanos, lideranças comunitárias.",  
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Critério de Sucesso": "Implementação bem-sucedida em um bairro-piloto e feedback positivo de produtores e consumidores."
  },
  
  "Rede de Troca de Livros": {
   "Problema": "Livros usados acumulam poeira e não são lidos.",
    "Solução": "Plataforma de troca de livros entre usuários.",
    "Público/Segmentos": "Leitores, estudantes, escolas.",
    "Canais": "Grupos de leitura, redes sociais, eventos literários.",
    "MVP": "Landing page com catálogo de 100 livros e sistema de troca.",
    "Validação": "50 trocas realizadas no primeiro mês e 100 usuários ativos.",
    "OKRs": "O: Criar comunidade de leitores; KR1: 200 usuários ativos; KR2: 100 trocas mensais.",
    "Forças": "Interesse crescente por sustentabilidade, comunidade literária engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com editoras e livrarias, expansão para outras cidades.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
  },

  "Central de Ofertas Comunitárias": {
    "Problema": "Ofertas locais se perdem em vários canais.",
    "Solução": "Hub único de promoções do bairro.",
    "Público/Segmentos": "Moradores locais, pequenos comerciantes.",
    "Canais": "Grupos de WhatsApp, redes sociais locais, associações de bairro.",
    "MVP": "Landing page com 10 ofertas e grupo de WhatsApp.",
    "Validação": "100 usuários ativos e 50 ofertas resgatadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de consumo local; KR1: 200 usuários ativos; KR2: 100 ofertas resgatadas.",
    "Forças": "Apoio à economia local, interesse por ofertas exclusivas.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria.",
    "Oportunidades": "Parcerias com comerciantes locais, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes plataformas, regulamentações locais.",

  },
  "Mercado de Permacultura Urbana":{

  "nomeDoProjeto": "EcoMercado Urbano",
  "Objetivo Principal": " Uma plataforma que conecta produtores de alimentos em pequena escala (hortas em telhados, pequenos quintais) com restaurantes locais e consumidores dispostos a pagar por produtos ultra-locais.",
  "Problema": "Moradores urbanos têm dificuldade em encontrar alimentos frescos e sustentáveis, enquanto pequenos produtores não têm um canal de vendas direto.",
  "Solução": "Uma plataforma online para que produtores de permacultura urbana vendam seus produtos, e consumidores assinem cestas semanais de alimentos locais.",
  "Solução Proposta": "Desenvolver um marketplace que conecte produtores e consumidores de permacultura urbana, com um sistema de assinaturas e entrega direta.",
  "Público/Segmentos": "Consumidores conscientes, moradores urbanos, restaurantes locais, pequenos produtores urbanos.",
  "Canais": "Feiras de bairro, redes sociais (grupos de alimentação saudável), parcerias com cafeterias e restaurantes.",
  "MVP": "Um site simples com um sistema de assinatura para 10 produtores e 50 clientes iniciais em um bairro específico.",
  "Validação": "Acompanhamento da frequência de pedidos semanais, feedback dos clientes e crescimento do número de produtores inscritos.",
  "Critérios de Aceite": "50 assinaturas ativas, 10 produtores registrados e uma taxa de satisfação de 90% dos clientes.",
  "OKRs": "O: Validar o modelo de negócio; KR1: 50 assinaturas ativas em 3 meses; KR2: 10 produtores na plataforma.",
  "Forças": "Crescente demanda por alimentos locais e orgânicos, forte apelo comunitário.",
  "Fraquezas": "Escalabilidade limitada por espaço físico, desafios logísticos de entrega, dependência de um pequeno número de produtores.",
  "Oportunidades": "Expansão para outros produtos sustentáveis, parcerias com restaurantes e escolas, educação sobre permacultura.",
  "Ameaças": "Concorrência de grandes redes de supermercados, regulamentações locais sobre venda de alimentos, sazonalidade dos produtos.",
  "Resumo": "EcoMercado Urbano é um marketplace que facilita a conexão entre produtores de alimentos em permacultura urbana e consumidores locais, promovendo um sistema alimentar mais justo e sustentável.",
  "Área de Atuação": "Alimentação, sustentabilidade, comunidade, tecnologia.",
  "Nível de Experiência": "Intermediário",
  "Recursos Disponíveis": "Plataforma online, rede de produtores urbanos, lideranças comunitárias.",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Preço Inicial": "Taxa de assinatura para consumidores, comissão sobre as vendas para os produtores.",
  "Receitas": "Comissão sobre vendas, taxa de assinatura, patrocínios de marcas sustentáveis.",
  "Recursos Disponíveis": "Plataforma online, rede de produtores urbanos, lideranças comunitárias.",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Critério de Sucesso": "Implementação bem-sucedida em um bairro-piloto e feedback positivo de produtores e consumidores."
  },

  "Assistente de Cozinha por Visão Computacional":{
  "nomeDoProjeto": "Cozinha Inteligente AI",
  "Nome do Projeto": "Cozinha Inteligente AI",
  "Objetivo Principal": "Criar um assistente de cozinha que reconhece ingredientes e sugere receitas, reduzindo o desperdício de alimentos.",
  "Problema": "Muitas pessoas não sabem o que cozinhar com os ingredientes que têm, resultando em desperdício de comida e compra de itens desnecessários.",
  "Solução": "Um aplicativo que usa a câmera do smartphone e visão computacional para identificar ingredientes na geladeira e despensa, gerando receitas personalizadas em tempo real.",
  "Solução Proposta": "Desenvolver um app de assistente de cozinha com IA que reconhece ingredientes, sugere receitas e cria listas de compras inteligentes.",
  "Público/Segmentos": "Pessoas que cozinham em casa, estudantes universitários, casais jovens, famílias que querem reduzir o desperdício de alimentos.",
  "Canais": "Google Play e Apple App Store, marketing de conteúdo em blogs de culinária e redes sociais, parcerias com influenciadores de alimentação saudável.",
  "MVP": "Um aplicativo com capacidade de reconhecer 20 ingredientes comuns e sugerir 50 receitas, com um módulo de lista de compras.",
  "Validação": "Coleta de dados sobre a frequência de uso, número de receitas criadas e feedback dos usuários sobre a utilidade das receitas sugeridas.",
  "Critérios de Aceite": "Reconhecimento de 20 ingredientes com 95% de precisão, 500 downloads no primeiro mês, 50% de usuários retornando semanalmente.",
  "OKRs": "O: Aumentar o uso do app; KR1: 50% de retenção de usuários mensais; KR2: 100 receitas personalizadas criadas por usuário.",
  "Forças": "Tecnologia inovadora, solução prática para um problema comum, potencial para integrações com outros serviços.",
  "Fraquezas": "Desafio técnico do reconhecimento de objetos em diferentes condições de iluminação, custo de treinamento do modelo de IA, dependência de uma base de dados de receitas robusta.",
  "Oportunidades": "Parcerias com supermercados e marcas de alimentos, expansão para o reconhecimento de validade de produtos e automação da lista de compras.",
  "Orçamento Inicial": "R$ 50.000 para desenvolvimento inicial, marketing e testes.",
  "Ameaças": "Concorrência de apps de receitas tradicionais, privacidade e segurança dos dados do usuário, mudanças rápidas na tecnologia de IA.",
  "Resumo": "Cozinha Inteligente AI é um app que usa visão computacional para ajudar as pessoas a cozinhar com o que têm, combatendo o desperdício e tornando a experiência culinária mais eficiente.",
  "Área de Atuação": "Alimentação, tecnologia, inteligência artificial, estilo de vida.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Equipe de desenvolvedores de IA, dataset de imagens de ingredientes, UX/UI designers.",
  "Prazo Desejado": "6 meses para um MVP funcional e validado.",
  "Preço Inicial": "Modelo freemium, com funcionalidades premium para assinatura (ex: receitas exclusivas, reconhecimento avançado).",
  "Receitas": "Assinaturas premium, parcerias com marcas de alimentos, publicidade direcionada.",
  "Critério de Sucesso": "Implementação bem-sucedida do reconhecimento de ingredientes, alto engajamento do usuário e redução do desperdício de alimentos relatada.",
  "Problema Central": "Muitas pessoas não sabem o que cozinhar com os ingredientes que têm, resultando em desperdício de comida e compra de itens desnecessários.",
  "Público-Alvo": "Pessoas que cozinham em casa, estudantes universitários, casais jovens, famílias que querem reduzir o desperdício de alimentos.",
  },
  
  "Mercado de Cursos de Micro-Aprendizagem":{
    
  "nomeDoProjeto": "MicroSaberes",
  "Nome do Projeto": "MicroSaberes",
  "Objetivo Principal": "Uma plataforma onde especialistas podem vender 'micro-aulas' de 1 a 2 minutos sobre tópicos específicos, perfeitas para serem consumidas durante pausas curtas.",
  "Problema": "A maioria dos cursos online é longa e exige um grande investimento de tempo, o que leva à baixa taxa de conclusão e desinteresse.",
  "Problema Central": "A maioria dos cursos online é longa e exige um grande investimento de tempo, o que leva à baixa taxa de conclusão e desinteresse.",
  "Público Alvo": "Profissionais ocupados, estudantes, pessoas que buscam aprender habilidades específicas rapidamente, especialistas que querem monetizar seu conhecimento.",
  "Solução": "Um marketplace de cursos focados em 'micro-aprendizagem', onde o conteúdo é dividido em pequenas pílulas de conhecimento, perfeitas para serem consumidas em pausas curtas do dia a dia.",
  "Solução Proposta": "Desenvolver um marketplace que conecte especialistas a alunos, onde a compra e venda de conhecimento é feita em pequenos módulos de vídeo ou texto.",
  "Público/Segmentos": "Profissionais ocupados, estudantes, pessoas que buscam aprender habilidades específicas rapidamente, especialistas que querem monetizar seu conhecimento.",
  "Canais": "Google Play e Apple App Store, marketing de conteúdo com 'micro-dicas', parcerias com empresas para treinamento corporativo.",
  "MVP": "Uma plataforma web com 5 especialistas e 20 micro-cursos, com um sistema de pagamento simples para aulas individuais.",
  "Validação": "Acompanhamento da taxa de conclusão das micro-aulas, feedback dos usuários sobre a utilidade do conteúdo e a frequência de compras de novos módulos.",
  "Critérios de Aceite": "5 especialistas ativos, 20 micro-cursos publicados e 100 vendas no primeiro mês.",
  "OKRs": "O: Validar o formato de micro-aprendizagem; KR1: 90% de taxa de conclusão das aulas; KR2: 500 compras de micro-aulas em 3 meses.",
  "Forças": "Formato inovador e alinhado com o ritmo de vida moderno, baixo custo de produção para especialistas, alta taxa de conclusão.",
  "Fraquezas": "Pode ser visto como 'conhecimento superficial', dificuldade em construir uma comunidade engajada, concorrência com grandes plataformas de e-learning.",
  "Oportunidades": "Expansão para treinamentos corporativos, criação de 'trilhas' de micro-cursos para certificação, gamificação do aprendizado.",
  "Orçamento Inicial": "R$ 30.000 para desenvolvimento da plataforma, marketing inicial e onboarding de especialistas.",
  "Ameaças": "Youtube e redes sociais oferecem conteúdo gratuito, pirataria de cursos, dependência da qualidade dos especialistas.",
  "Resumo": "MicroSaberes é um marketplace que revoluciona o aprendizado online, conectando especialistas e alunos através de cursos curtos e práticos, perfeitos para a vida moderna.",
  "Área de Atuação": "Educação, tecnologia, e-learning, produtividade.",
  "Nível de Experiência": "Intermediário",
  "Recursos Disponíveis": "Plataforma online, rede de especialistas, ferramentas de gravação e edição simples.",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Preço Inicial": "Preço fixo por micro-aula ou pacote de aulas (ex: R$5-R$10 por aula).",
  "Receitas": "Comissão sobre as vendas de cada curso, assinaturas para acesso ilimitado.",
  "Critério de Sucesso": "Alto volume de vendas de micro-aulas, feedback positivo de especialistas e alunos, alta taxa de conclusão de cursos.",
  "Descrição Geral": "MicroSaberes é um marketplace que revoluciona o aprendizado online, conectando especialistas e alunos através de cursos curtos e práticos, perfeitos para a vida moderna.",

  },
  "Terapia Imersiva em VR":{
  
  "nomeDoProjeto": "MindScape VR",
  "Objetivo Principal": "Uma plataforma de realidade virtual onde psicólogos podem conduzir sessões de terapia em ambientes virtuais calmos e controlados, ajudando no tratamento de fobias e ansiedade.",
  "Problema": "A terapia tradicional nem sempre é eficaz para expor pacientes a gatilhos de forma controlada, e o acesso a ambientes calmos e seguros é limitado.",
  "Solução": "Uma plataforma de VR que oferece ambientes virtuais terapêuticos e guiados, onde psicólogos podem conduzir sessões de exposição e relaxamento de forma segura e controlada.",
  "Solução Proposta": "Desenvolver um software e um conjunto de ambientes em VR para terapia, com um módulo de monitoramento de biofeedback e interface para o terapeuta.",
  "Público/Segmentos": "Psicólogos, terapeutas, clínicas de saúde mental, pacientes que sofrem de ansiedade, estresse pós-traumático e fobias.",
  "Canais": "Parcerias com clínicas de psicologia e hospitais, congressos de saúde mental, marketing digital focado em profissionais da área.",
  "MVP": "Um aplicativo de VR com três ambientes (praia, floresta, espaço neutro) e um módulo básico de monitoramento, validado por 10 terapeutas.",
  "Validação": "Feedback dos terapeutas e pacientes sobre a eficácia da terapia em VR, número de sessões realizadas na plataforma e redução dos sintomas.",
  "Critérios de Aceite": "10 terapeutas validando a plataforma, uso em pelo menos 50 sessões de terapia, redução de sintomas relatada pelos pacientes.",
  "OKRs": "O: Validar a eficácia da terapia em VR; KR1: 50% de redução nos sintomas de ansiedade; KR2: 10 terapeutas usando ativamente o sistema.",
  "Forças": "Ambientes controláveis e seguros, possibilidade de exposição gradual, potencial de escalabilidade para um grande número de pacientes.",
  "Fraquezas": "Custo inicial alto para o hardware de VR, necessidade de treinamento para terapeutas, potencial de causar enjoo em alguns usuários.",
  "Oportunidades": "Expansão para outras áreas (treinamento de cirurgiões, terapia ocupacional), parcerias com fabricantes de hardware VR, teleterapia.",
  "Ameaças": "Concorrência de outras plataformas de VR, regulamentações rigorosas na área da saúde, ceticismo de parte da comunidade médica.",
  "Resumo": "MindScape VR é uma ferramenta inovadora que utiliza a realidade virtual para oferecer ambientes de terapia imersiva, melhorando o tratamento de transtornos mentais e a experiência de terapeutas e pacientes.",
  "Área de Atuação": "Saúde mental, tecnologia, realidade virtual, telemedicina.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Equipe de desenvolvedores de VR, psicólogos consultores, hardware de VR para testes.",
  "Prazo Desejado": "12 meses para o lançamento de um MVP robusto e validado clinicamente.",
  "Preço Inicial": "Modelo de assinatura para terapeutas, com preço por paciente ou por sessão.",
  "Receitas": "Assinaturas de terapeutas, licenças para clínicas e hospitais.",
  "Critério de Sucesso": "Implementação em clínicas de saúde, feedback positivo de terapeutas e pacientes, publicação de estudos de caso."
},
"Cofre de Herança Digital":
{
  "nomeDoProjeto": "Cofre de Herança Digital",
  "Objetivo Principal": "Garantir a transferência segura de senhas, dados pessoais e mensagens curtas para um herdeiro designado em caso de falecimento ou incapacidade.",
  "Problema": "A perda de um ente querido muitas vezes resulta na perda do acesso a contas digitais, memórias e dados importantes, devido à falta de um sistema de herança digital.",
  "Solução": "Uma plataforma criptografada e segura onde os usuários podem armazenar senhas, documentos pessoais e mensagens curtas, designando um herdeiro que terá acesso aos dados mediante prova de falecimento ou incapacidade.",
  "Solução Proposta": "Desenvolver um serviço digital para armazenamento seguro de ativos digitais, com um sistema de validação e transferência automática para um herdeiro.",
  "Público/Segmentos": "Pessoas com muitas contas digitais, idosos, famílias que buscam planejar o futuro, profissionais liberais.",
  "Canais": "Parcerias com escritórios de advocacia, planejadores financeiros, seguros de vida, marketing digital focado em segurança e planejamento familiar.",
  "MVP": "Uma plataforma com criptografia de ponta para armazenamento de 5 senhas e 1 documento, com a designação de um único herdeiro e um processo manual de validação.",
  "Validação": "Implementação com um grupo-piloto de usuários, buscando feedback sobre a segurança, a facilidade de uso e a confiabilidade do processo de transferência.",
  "Critérios de Aceite": "Plataforma com criptografia funcional, 100 usuários-piloto cadastrados e um processo de transferência testado com sucesso.",
  "OKRs": "O: Estabelecer confiança no serviço; KR1: 95% de satisfação dos usuários-piloto; KR2: Zero falhas na transferência de dados.",
  "Forças": "Foco em um problema crescente, alta segurança e criptografia de ponta, valor emocional e prático para o usuário.",
  "Fraquezas": "Custo de desenvolvimento de segurança, desafios legais e regulatórios, barreira de entrada para usuários menos familiarizados com tecnologia.",
  "Oportunidades": "Expansão para outros tipos de ativos (criptomoedas, NFTs), parcerias com bancos e instituições financeiras, integração com cartórios e sistemas legais.",
  "Ameaças": "Risco de ataques cibernéticos, concorrência de soluções tradicionais (testamento em papel), regulamentação governamental restritiva.",
  "Resumo": "Cofre de Herança Digital é uma solução segura para a transferência de ativos digitais, garantindo que senhas, documentos e mensagens curtas sejam passadas para as próximas gerações.",
  "Área de Atuação": "Segurança digital, tecnologia, finanças, legal tech.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Desenvolvedores especializados em criptografia e segurança, consultores jurídicos, plataforma de armazenamento em nuvem segura.",
  "Prazo Desejado": "12 meses para o MVP, com validação e feedback de especialistas.",
  "Preço Inicial": "Modelo de assinatura mensal para armazenamento contínuo, com opções de planos baseadas na quantidade de dados.",
  "Receitas": "Assinaturas mensais, taxas por transferência, serviços adicionais de consultoria jurídica digital.",
  "Critério de Sucesso": "Implementação bem-sucedida de um sistema de segurança robusto, alta confiança dos usuários e um processo de transferência de dados confiável e sem falhas."
},
"Plataforma de Curadoria de Notícias (Anti-Bolhas)":
{
  "nomeDoProjeto": "EchoSphere",
  "Objetivo Principal": "Criar uma plataforma que apresenta notícias de diferentes perspectivas políticas e ideológicas, combatendo a polarização e a 'bolha de filtro'.",
  "Problema": "Algoritmos de redes sociais e agregadores de notícias criam 'bolhas de filtro', onde os usuários são expostos apenas a informações que confirmam suas próprias crenças, aumentando a polarização.",
  "Solução": "Uma plataforma de curadoria de notícias que utiliza IA para analisar o espectro ideológico das fontes e apresenta notícias de forma equilibrada, mostrando diferentes pontos de vista sobre o mesmo evento.",
  "Solução Proposta": "Desenvolver um agregador de notícias que usa IA para classificar artigos por viés ideológico e apresentá-los lado a lado, incentivando o pensamento crítico e a exposição a novas ideias.",
  "Público/Segmentos": "Cidadãos engajados, jornalistas, acadêmicos, estudantes, pessoas que buscam entender diferentes pontos de vista.",
  "Canais": "Google Play e Apple App Store, marketing de conteúdo com artigos sobre viés de confirmação e desinformação, parcerias com universidades e centros de pesquisa.",
  "MVP": "Um aplicativo móvel que curadoria notícias de 10 fontes diferentes, classificando-as em 3 categorias de viés (esquerda, centro, direita), com um recurso de comparação de artigos.",
  "Validação": "Acompanhamento da retenção de usuários, feedback sobre a utilidade do recurso de comparação e coleta de dados sobre a diversidade de fontes que os usuários consomem.",
  "Critérios de Aceite": "1.000 downloads no primeiro mês, 50% de usuários usando o recurso de comparação semanalmente, feedback positivo sobre a neutralidade da plataforma.",
  "OKRs": "O: Aumentar a exposição dos usuários a diferentes ideias; KR1: 50% dos usuários consumindo conteúdo de fontes diversas; KR2: Zero reclamações de viés da plataforma.",
  "Forças": "Aborda um problema social relevante e urgente, tecnologia inovadora, potencial para se tornar uma ferramenta educacional e cívica.",
  "Fraquezas": "Desafio técnico de classificar o viés de forma neutra, risco de ser acusada de viés ideológico, dependência da qualidade das fontes de notícias.",
  "Oportunidades": "Expansão para outros idiomas e países, integração com redes sociais para identificar a 'bolha' do usuário, parcerias com plataformas de checagem de fatos.",
  "Ameaças": "Concorrência de grandes plataformas de notícias, campanhas de desinformação para desacreditar o serviço, regulamentações governamentais sobre a liberdade de imprensa.",
  "Resumo": "EchoSphere é uma plataforma de notícias que utiliza IA para quebrar a 'bolha de filtro', apresentando diferentes perspectivas sobre o mesmo evento e promovendo um consumo de informação mais equilibrado e crítico.",
  "Área de Atuação": "Jornalismo, tecnologia, IA, cívica, educação.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Equipe de desenvolvedores de IA e processamento de linguagem natural (NLP), cientistas de dados, jornalistas e especialistas em mídia.",
  "Prazo Desejado": "9 meses para o lançamento do MVP e validação inicial.",
  "Preço Inicial": "Modelo freemium, com acesso básico gratuito e recursos avançados (análise de profundidade, acesso a fontes premium) em um plano de assinatura.",
  "Receitas": "Assinaturas premium, parcerias com centros de pesquisa e universidades, publicidade contextual (sem rastreamento de usuário).",
  "Critério de Sucesso": "Implementação bem-sucedida do algoritmo de classificação de viés, crescimento da base de usuários e reconhecimento como uma ferramenta confiável para combater a polarização."
},
"Cidadania Ciberfísica":
{
  "nomeDoProjeto": "Cidade Gêmea",
  "Objetivo Principal": "Criar uma plataforma digital interativa que representa e simula uma cidade real em tempo real, permitindo aos cidadãos interagir com a gestão urbana.",
  "Problema": "A participação cívica em grandes cidades é baixa devido à burocracia, falta de transparência e distância entre cidadãos e gestores públicos.",
  "Solução": "Um 'gêmeo digital' da cidade, com uma interface gamificada onde os cidadãos podem votar em pautas, propor projetos, reportar problemas urbanos e visualizar o impacto em tempo real.",
  "Solução Proposta": "Desenvolver uma plataforma de visualização de dados urbanos com um módulo de participação cívica, conectando a réplica digital da cidade a dados reais (trânsito, infraestrutura, etc.).",
  "Público/Segmentos": "Cidadãos de grandes cidades, gestores públicos, urbanistas, engenheiros, ONGs.",
  "Canais": "Parcerias com prefeituras e órgãos governamentais, marketing digital em redes sociais, imprensa local, eventos de tecnologia cívica.",
  "MVP": "Um modelo 3D de uma praça pública que simula o impacto de diferentes projetos (ex: adicionar uma ciclovia) e permite que os cidadãos votem na melhor opção.",
  "Validação": "Monitoramento da participação nos eventos-piloto, feedback de cidadãos e gestores públicos sobre a usabilidade e eficácia da plataforma.",
  "Critérios de Aceite": "1.000 votos na pauta piloto, feedback positivo de gestores sobre a qualidade dos dados, 90% de satisfação dos cidadãos-participantes.",
  "OKRs": "O: Aumentar o engajamento cívico; KR1: 50% de participação em 3 meses na pauta piloto; KR2: 5 propostas de cidadãos implementadas em 6 meses.",
  "Forças": "Tecnologia de ponta (simulação em tempo real), potencial para democratizar a gestão urbana, valor para gestores e cidadãos.",
  "Fraquezas": "Alto custo de desenvolvimento e manutenção, desafio de integrar dados de diferentes fontes, barreira de entrada para cidadãos com baixa proficiência digital.",
  "Oportunidades": "Expansão para outras cidades, integração com sistemas de IoT urbanos, parcerias com universidades para pesquisa e desenvolvimento.",
  "Ameaças": "Desafios de segurança de dados, desinformação e ataques cibernéticos, resistência de gestores públicos a mudanças, falta de regulamentação clara.",
  "Resumo": "Cidade Gêmea é uma plataforma ciberfísica que usa simulação e dados em tempo real para transformar a participação cívica, unindo o mundo digital e físico de forma transparente e interativa.",
  "Área de Atuação": "Urbanismo, tecnologia cívica, IA, simulação, big data.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Desenvolvedores de simulação 3D, especialistas em urbanismo e dados, parcerias com prefeituras.",
  "Prazo Desejado": "18 meses para o lançamento de um MVP para uma área específica da cidade.",
  "Preço Inicial": "Modelo de licença para prefeituras, com planos baseados no tamanho da cidade e número de usuários.",
  "Receitas": "Licenças governamentais, taxas de consultoria para a implementação, vendas de dados anonimizados para urbanistas e pesquisadores.",
  "Critério de Sucesso": "Implementação em uma cidade, aumento significativo da participação cívica e reconhecimento como uma ferramenta eficaz de gestão urbana."
},
"Plataforma de Criação de Linguagem (IA-driven)":
{
  "nomeDoProjeto": "Conlang Creator",
  "Objetivo Principal": "Oferecer uma plataforma que usa IA para auxiliar escritores, designers de jogos e criadores de mundos a construir idiomas fictícios (conlangs).",
  "Problema": "A criação de uma língua fictícia convincente e com gramática consistente é um processo complexo e demorado que exige conhecimento linguístico aprofundado, sendo uma barreira para muitos criadores.",
  "Solução": "Uma ferramenta que utiliza modelos de linguagem de IA para sugerir fonemas, regras gramaticais e vocabulário, garantindo consistência e acelerando o processo de criação de uma conlang.",
  "Solução Proposta": "Desenvolver um software com uma interface amigável que guia o usuário na criação de um idioma fictício, desde a fonologia básica até a sintaxe e o léxico, com assistência de IA.",
  "Público/Segmentos": "Escritores de ficção, roteiristas, desenvolvedores de jogos (RPG, MMOs), linguistas amadores, fãs de ficção científica e fantasia.",
  "Canais": "Comunidades online de escritores e gamers, fóruns de linguística, marketing de conteúdo com exemplos de idiomas criados, parcerias com estúdios de jogos.",
  "MVP": "Uma versão web que permite a criação de um sistema de escrita e um vocabulário básico de 100 palavras, com sugestões de IA para a pronúncia e a morfologia.",
  "Validação": "Feedback de escritores e desenvolvedores de jogos sobre a utilidade da ferramenta, monitoramento da frequência de uso e da quantidade de idiomas criados.",
  "Critérios de Aceite": "100 idiomas criados na plataforma por um grupo-piloto, feedback positivo de 90% dos usuários sobre a facilidade de uso da IA.",
  "OKRs": "O: Tornar a criação de conlangs acessível; KR1: 50% dos usuários completando a criação de uma fonologia; KR2: 1.000 palavras geradas por IA em 6 meses.",
  "Forças": "Resolve um problema específico e de nicho, uso inovador de IA para criatividade, grande potencial de engajamento da comunidade de fãs.",
  "Fraquezas": "Desafio técnico em criar um modelo de IA que entenda a complexidade da linguística, concorrência de ferramentas manuais e dicionários online, ceticismo de linguistas profissionais.",
  "Oportunidades": "Integração com outras plataformas de escrita e desenvolvimento de jogos, expansão para criação de idiomas para realidade virtual, parcerias com universidades.",
  "Ameaças": "Desafios de direitos autorais para as línguas geradas pela IA, dependência de tecnologia de terceiros (modelos de IA), concorrência de soluções gratuitas.",
  "Resumo": "Conlang Creator é a primeira plataforma assistida por IA que torna a criação de línguas fictícias acessível e divertida para todos os criadores, de escritores a desenvolvedores de jogos.",
  "Área de Atuação": "Inteligência Artificial, escrita, jogos, linguística, criatividade.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Equipe de desenvolvedores de IA e linguistas computacionais, dataset de línguas construídas (conlangs), designers de UX/UI.",
  "Prazo Desejado": "12 meses para o lançamento de um MVP e validação com o público-alvo.",
  "Preço Inicial": "Modelo freemium, com recursos básicos gratuitos e um plano de assinatura para funcionalidades avançadas (gramática complexa, exportação, etc.).",
  "Receitas": "Assinaturas premium, licenciamento da ferramenta para estúdios de jogos e cinema, vendas de pacotes de idiomas pré-prontos.",
  "Critério de Sucesso": "Implementação de um modelo de IA consistente, feedback positivo de criadores de conteúdo e crescimento da base de usuários ativos."
},
"Plataforma de Compartilhamento de Conhecimento Local":
{
  "nomeDoProjeto": "SaberLocal",
  "Objetivo Principal": "Criar uma plataforma que conecte moradores para a troca de conhecimentos e habilidades em nível local.",
  "Problema": "Muitas pessoas possuem conhecimentos e habilidades úteis (culinária, jardinagem, reparos) que não são compartilhados, enquanto outras buscam aprender, mas não sabem onde encontrar ajuda na própria comunidade.",
  "Solução": "Uma rede social ou marketplace que permite que usuários criem perfis, listem suas habilidades e conhecimentos e se conectem com vizinhos para aulas, workshops ou trocas informais.",
  "Solução Proposta": "Desenvolver um aplicativo ou site que facilite a descoberta de especialistas e o agendamento de encontros para a troca de conhecimentos entre moradores de um mesmo bairro ou cidade.",
  "Público/Segmentos": "Moradores de bairros, aposentados, artesãos, professores, famílias que buscam atividades para aprender, recém-chegados a uma cidade.",
  "Canais": "Grupos de bairro em redes sociais, cartazes em centros comunitários, parcerias com escolas e bibliotecas locais, eventos de lançamento em feiras de bairro.",
  "MVP": "Um grupo no WhatsApp ou Telegram com um formulário de cadastro, onde os usuários listam suas habilidades e os administradores fazem a conexão inicial.",
  "Validação": "Monitoramento da atividade do grupo-piloto, feedback dos usuários sobre a utilidade das conexões e a quantidade de encontros de troca de conhecimento.",
  "Critérios de Aceite": "100 membros no grupo-piloto, 20 trocas de conhecimento documentadas em 3 meses, feedback positivo dos participantes.",
  "OKRs": "O: Promover a troca de saberes na comunidade; KR1: 50% dos membros do grupo-piloto oferecendo uma habilidade; KR2: 10 workshops comunitários organizados em 6 meses.",
  "Forças": "Forte senso de comunidade, baixo custo inicial para o MVP, foco em sustentabilidade e economia circular.",
  "Fraquezas": "Desafios de escalabilidade, dificuldade de monetização, questões de segurança e confiança entre os usuários.",
  "Oportunidades": "Expansão para outros bairros e cidades, parcerias com pequenas empresas locais, criação de um modelo de 'economia da partilha'.",
  "Ameaças": "Concorrência de plataformas maiores e mais genéricas, desinteresse da comunidade, dificuldade em moderar o conteúdo e a segurança dos encontros.",
  "Resumo": "SaberLocal é uma plataforma que conecta a comunidade por meio do conhecimento, permitindo que as pessoas compartilhem suas habilidades e aprendam com seus vizinhos, fortalecendo os laços comunitários e o saber local.",
  "Área de Atuação": "Comunidade, educação, tecnologia, economia da partilha.",
  "Nível de Experiência": "Iniciante a Intermediário",
  "Recursos Disponíveis": "Redes sociais, voluntários da comunidade, um desenvolvedor para o MVP.",
  "Prazo Desejado": "3 meses para o MVP e validação inicial.",
  "Preço Inicial": "Modelo freemium, com acesso gratuito e funcionalidades premium para organizadores de workshops ou para acesso a especialistas verificados.",
  "Receitas": "Assinaturas premium, comissão sobre workshops pagos, publicidade de empresas locais, doações da comunidade.",
  "Critério de Sucesso": "Implementação bem-sucedida em um bairro-piloto, alto engajamento da comunidade e feedback positivo sobre o impacto na vida dos moradores."
},
"Kit de Bio-Hacking para Casa":
{
  "nomeDoProjeto": "Bio-Lab em Casa",
  "Objetivo Principal": "Oferecer kits de assinatura seguros e educacionais para que pessoas de todas as idades possam realizar experimentos de biologia básica em casa.",
  "Problema": "O aprendizado de biologia e genética pode ser abstrato. Kits e laboratórios são caros e inacessíveis para a maioria das pessoas, limitando a curiosidade e o aprendizado prático.",
  "Solução": "Um serviço de assinatura que entrega, mensalmente, kits com materiais e guias detalhados para experimentos de baixo risco, como a extração de DNA de frutas ou o cultivo de microrganismos inofensivos.",
  "Solução Proposta": "Desenvolver um serviço de assinatura que fornece kits com reagentes e instruções seguras para experimentos de biologia, com tutoriais em vídeo e uma comunidade online para suporte.",
  "Público/Segmentos": "Estudantes, pais que praticam ensino em casa, escolas, professores, entusiastas de ciência, curiosos sobre biologia e genética.",
  "Canais": "E-commerce próprio, marketing de conteúdo com tutoriais e artigos científicos populares, parcerias com escolas e feiras de ciências, redes sociais com foco em ciência.",
  "MVP": "Um kit de extração de DNA de morango, com todos os reagentes e um guia ilustrado. O MVP seria um site simples para venda do kit e um canal no YouTube com o tutorial em vídeo.",
  "Validação": "Venda de 100 kits-piloto e coleta de feedback sobre a experiência de uso, clareza das instruções e qualidade dos materiais.",
  "Critérios de Aceite": "100 kits vendidos em 3 meses, 90% de feedback positivo dos usuários sobre a experiência e segurança, 80% de taxa de sucesso nos experimentos.",
  "OKRs": "O: Tornar a biologia divertida e acessível; KR1: 50% de taxa de recompra de kits; KR2: 1.000 visualizações no tutorial do YouTube.",
  "Forças": "Aborda um nicho de mercado crescente (edutainment), baixo risco, grande potencial para conteúdo viral e engajamento da comunidade.",
  "Fraquezas": "Desafios logísticos com reagentes, necessidade de garantir a segurança dos kits, educar o público sobre o conceito de 'bio-hacking' seguro.",
  "Oportunidades": "Expansão para kits mais avançados, parcerias com museus de ciência, criação de uma comunidade online para compartilhar resultados, kits para escolas.",
  "Ameaças": "Concorrência de soluções gratuitas na internet, regulamentação de materiais biológicos (se o projeto evoluir), desinformação sobre segurança.",
  "Resumo": "Bio-Lab em Casa é um serviço de assinatura que desmistifica a biologia, oferecendo kits seguros e divertidos para que entusiastas e estudantes possam explorar a ciência de forma prática e interativa em suas próprias casas.",
  "Área de Atuação": "Educação, ciência, tecnologia, e-commerce.",
  "Nível de Experiência": "Iniciante",
  "Recursos Disponíveis": "Químico consultor, designers de instruções, plataforma de e-commerce, equipe de marketing.",
  "Prazo Desejado": "6 meses para lançamento do MVP e validação inicial.",
  "Preço Inicial": "Modelo de assinatura mensal, com kits temáticos a cada mês (ex: DNA, fermentação, microbiologia).",
  "Receitas": "Assinaturas mensais, vendas avulsas de kits, vendas de materiais adicionais (ex: microscópios de brinquedo).",
  "Critério de Sucesso": "Implementação bem-sucedida do modelo de assinatura, alta taxa de retenção de clientes e feedback positivo sobre a experiência de aprendizado."
},
"Assistente de Organização Familiar":
{
  "nomeDoProjeto": "Family Flow",
  "Objetivo Principal": "Oferecer uma plataforma colaborativa para que as famílias possam gerenciar tarefas, compromissos e finanças de forma integrada.",
  "Problema": "A desorganização e a falta de comunicação nas famílias geram estresse, compromissos perdidos e uma divisão de tarefas desigual.",
  "Solução": "Um aplicativo que centraliza listas de tarefas, calendários, listas de compras e um painel de finanças, permitindo que todos os membros da família contribuam e visualizem a organização da casa em tempo real.",
  "Solução Proposta": "Desenvolver um app com funcionalidades de listas de tarefas compartilhadas, calendário familiar, controle de despesas e um chat para comunicação interna da família.",
  "Público/Segmentos": "Famílias com crianças, casais que moram juntos, estudantes em moradias compartilhadas, famílias com rotinas atarefadas.",
  "Canais": "Google Play e Apple App Store, blogs e sites de maternidade/organização, redes sociais (Instagram, Pinterest), indicações de usuários.",
  "MVP": "Um aplicativo com listas de tarefas e um calendário familiar compartilhável, disponível para até 5 membros da família.",
  "Validação": "Coleta de feedback de um grupo-piloto de 20 famílias, monitorando a frequência de uso das funcionalidades e a percepção de melhoria na organização.",
  "Critérios de Aceite": "100 downloads no primeiro mês, 50% dos usuários ativos semanalmente e 80% de satisfação com a ferramenta de calendário.",
  "OKRs": "O: Aumentar a organização familiar; KR1: 50% de adesão de todos os membros da família; KR2: Reduzir em 30% o número de compromissos esquecidos.",
  "Forças": "Resolve um problema comum e real, potencial para viralizar por indicações, alta utilidade para o dia a dia.",
  "Fraquezas": "Concorrência com outras plataformas de organização, dificuldade em engajar todos os membros da família, necessidade de um design muito intuitivo.",
  "Oportunidades": "Integração com assistentes de voz (Alexa, Google Assistant), módulos de gerenciamento de finanças mais robustos, parcerias com marcas de produtos para casa.",
  "Ameaças": "Novas funcionalidades em aplicativos de calendário já existentes, perda de interesse se o app não for fácil de usar.",
  "Resumo": "Family Flow é o assistente de organização familiar que centraliza tarefas e agendas, promovendo a comunicação e reduzindo o estresse do dia a dia da casa.",
  "Área de Atuação": "Casa e Família, produtividade, tecnologia, estilo de vida.",
  "Nível de Experiência": "Intermediário",
  "Recursos Disponíveis": "Equipe de desenvolvedores, designers de UX/UI, grupo de famílias para testes.",
  "Prazo Desejado": "6 meses para o lançamento do MVP.",
  "Preço Inicial": "Modelo freemium, com acesso básico gratuito e uma versão premium com mais funcionalidades para a família toda.",
  "Receitas": "Assinaturas premium, parcerias com marcas e publicidade não invasiva.",
  "Critério de Sucesso": "Crescimento da base de usuários, alta taxa de retenção e feedback positivo sobre a melhoria da qualidade de vida familiar."
},
"Economia Circular em Casa":
{
  "nomeDoProjeto": "Reuso Local",
  "Objetivo Principal": "Criar um marketplace de itens usados em nível de bairro ou condomínio, promovendo a economia circular e a sustentabilidade local.",
  "Problema": "Muitas pessoas têm itens em bom estado que não usam, mas têm dificuldade em vendê-los ou trocá-los localmente, enquanto o descarte inadequado de produtos contribui para o desperdício.",
  "Solução": "Uma plataforma focada na comunidade, onde vizinhos podem anunciar e comprar ou trocar itens usados de forma segura e prática, como roupas, móveis, brinquedos e livros.",
  "Solução Proposta": "Desenvolver um app que permite a criação de anúncios de produtos usados, com um sistema de geolocalização para conectar vendedores e compradores no mesmo bairro.",
  "Público/Segmentos": "Famílias com crianças em crescimento, pessoas que estão se mudando, estudantes, entusiastas de sustentabilidade, ONGs locais.",
  "Canais": "Grupos de Facebook de bairros, comunidades de WhatsApp, panfletos em centros comunitários, parcerias com eventos locais de troca de roupas.",
  "MVP": "Uma plataforma web que permite o cadastro de itens por categoria e a busca por proximidade, com um chat para negociação direta entre os usuários.",
  "Validação": "Análise do volume de transações e interações entre os usuários no bairro-piloto, feedback sobre a segurança e a usabilidade da plataforma.",
  "Critérios de Aceite": "100 itens cadastrados, 20 transações realizadas e 80% de feedback positivo sobre a experiência de compra e venda local.",
  "OKRs": "O: Promover a sustentabilidade local; KR1: 50% dos itens cadastrados sendo vendidos/trocados; KR2: 100 usuários ativos no bairro-piloto em 3 meses.",
  "Forças": "Forte apelo à sustentabilidade e economia, baixo custo de aquisição de clientes por meio da comunidade, resolve um problema local de logística.",
  "Fraquezas": "Desafios de confiança e segurança entre vizinhos, dependência de um número mínimo de usuários para funcionar, concorrência com grandes marketplaces.",
  "Oportunidades": "Expansão para aluguel de itens (ferramentas, equipamentos), parcerias com empresas de reciclagem e upcycling, gamificação para incentivar a sustentabilidade.",
  "Ameaças": "Problemas com a moderação de anúncios, falta de engajamento da comunidade após o lançamento, desafios de segurança nas transações.",
  "Resumo": "Reuso Local é a plataforma que transforma vizinhos em uma rede de economia circular, facilitando a troca e a venda de itens usados e promovendo um estilo de vida mais sustentável em nível de bairro.",
  "Área de Atuação": "Sustentabilidade, comunidade, e-commerce, economia compartilhada.",
  "Nível de Experiência": "Intermediário",
  "Recursos Disponíveis": "Desenvolvedores, designers de comunidade, voluntários locais para divulgação.",
  "Prazo Desejado": "4 meses para o lançamento do MVP.",
  "Preço Inicial": "Modelo de comissão sobre vendas (opcional), doações da comunidade para manutenção da plataforma, publicidade de empresas locais.",
  "Receitas": "Taxas de comissão por transação, publicidade de empresas sustentáveis, funcionalidades premium (ex: destaque de anúncios).",
  "Critério de Sucesso": "Alto volume de transações na plataforma, crescimento orgânico da base de usuários e reconhecimento como uma ferramenta de sustentabilidade local."
},
"Plataforma de Suporte para Saúde Mental":
{
  "nomeDoProjeto": "Círculo de Apoio",
  "Objetivo Principal": "Criar uma plataforma anônima e segura para que pessoas com problemas de saúde mental possam se conectar e receber apoio de uma comunidade moderada.",
  "Problema": "Muitas pessoas se sentem isoladas ao lidar com problemas de saúde mental, e a estigmatização impede que busquem ajuda ou compartilhem suas experiências, dificultando a busca por suporte.",
  "Solução": "Uma plataforma social onde os usuários podem participar de grupos de apoio, compartilhar suas histórias de forma anônima e interagir com uma comunidade moderada por profissionais de saúde mental, proporcionando um ambiente seguro e acolhedor.",
  "Solução Proposta": "Desenvolver um aplicativo com fóruns temáticos, um sistema de anonimato para os usuários, e uma equipe de moderação treinada para garantir a segurança e a qualidade das interações.",
  "Público/Segmentos": "Pessoas que sofrem de ansiedade, depressão, burnout, transtornos alimentares, e qualquer pessoa que busque um espaço para falar sobre saúde mental.",
  "Canais": "Google Play e Apple App Store, parcerias com psicólogos e clínicas, marketing de conteúdo em blogs de saúde mental, campanhas de conscientização nas redes sociais.",
  "MVP": "Um aplicativo com três fóruns temáticos (ex: ansiedade, depressão, burnout) e uma equipe de moderação inicial, permitindo a postagem de textos anônimos e a interação por meio de comentários.",
  "Validação": "Implementação com um grupo-piloto de 100 usuários, buscando feedback sobre a segurança do anonimato, a qualidade da moderação e a sensação de pertencimento à comunidade.",
  "Critérios de Aceite": "1.000 posts anônimos no primeiro mês, 95% de satisfação com a moderação e zero incidentes de bullying ou toxicidade no grupo-piloto.",
  "OKRs": "O: Promover um ambiente seguro e acolhedor; KR1: 90% de engajamento da comunidade em 3 meses; KR2: 100% das postagens moderadas em menos de 10 minutos.",
  "Forças": "Resolve um problema social relevante, alto potencial de impacto social, comunidade como principal motor de crescimento.",
  "Fraquezas": "Desafio de moderação em larga escala, risco de toxicidade ou desinformação, necessidade de garantir o anonimato e a segurança dos dados.",
  "Oportunidades": "Integração com teleterapia, parcerias com empresas para programas de bem-estar corporativo, expansão para outras línguas e países.",
  "Ameaças": "Violações de dados, problemas de segurança, concorrência de grandes redes sociais que podem criar grupos de apoio, regulamentações rigorosas sobre dados de saúde.",
  "Resumo": "Círculo de Apoio é uma plataforma digital que oferece um espaço anônimo e moderado para que pessoas com problemas de saúde mental possam se conectar, compartilhar suas experiências e encontrar suporte na comunidade.",
  "Área de Atuação": "Saúde mental, tecnologia, comunidade, bem-estar.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Equipe de desenvolvedores, psicólogos consultores para moderação, equipe de segurança digital.",
  "Prazo Desejado": "9 meses para o lançamento de um MVP funcional e seguro.",
  "Preço Inicial": "Modelo freemium, com acesso básico gratuito e uma assinatura premium para acesso a grupos exclusivos e recursos avançados.",
  "Receitas": "Assinaturas premium, parcerias com empresas e planos corporativos, doações.",
  "Critério de Sucesso": "Crescimento sustentável da comunidade, alta satisfação dos usuários e reconhecimento como uma plataforma de apoio confiável e segura."
},
"Wellness Corporativo Gamificado":
{
  "nomeDoProjeto": "WellPlay Corporativo",
  "Objetivo Principal": "Aumentar o bem-estar e a produtividade dos funcionários de empresas através de um programa de gamificação de hábitos saudáveis.",
  "Problema": "Muitos funcionários de empresas sofrem de estresse, sedentarismo e falta de motivação, o que leva à baixa produtividade e ao absenteísmo.",
  "Solução": "Uma plataforma que transforma o bem-estar em um jogo, com desafios diários de exercícios, meditação e nutrição, recompensas, placares de líderes e competições entre equipes.",
  "Solução Proposta": "Desenvolver um aplicativo que integra rastreadores de atividades físicas, programas de meditação e receitas saudáveis, com um sistema de pontos e recompensas personalizáveis para as empresas.",
  "Público/Segmentos": "Empresas de médio e grande porte, departamentos de RH, funcionários de escritórios, equipes de trabalho remoto.",
  "Canais": "Vendas B2B para departamentos de RH e C-level, participação em eventos e feiras de tecnologia e recursos humanos, parcerias com startups de bem-estar.",
  "MVP": "Um aplicativo com desafios semanais de passos (integrado com wearables), um placar de líderes e um sistema de pontos que podem ser trocados por pequenos prêmios.",
  "Validação": "Implementação em uma empresa-piloto, medindo o engajamento dos funcionários (frequência de uso do app) e coletando feedback sobre a motivação e a sensação de bem-estar.",
  "Critérios de Aceite": "50% dos funcionários da empresa-piloto usando o app ativamente, 80% de satisfação com o programa e aumento de 15% na taxa de participação em atividades saudáveis.",
  "OKRs": "O: Melhorar a saúde e o engajamento dos funcionários; KR1: Reduzir em 10% o absenteísmo em 6 meses; KR2: Aumentar em 20% a participação em atividades de bem-estar.",
  "Forças": "Aborda uma necessidade crescente no mercado corporativo, usa gamificação para incentivar comportamentos positivos, potencial para criar uma cultura de bem-estar.",
  "Fraquezas": "Custo para as empresas, desafio de engajar funcionários com diferentes perfis, necessidade de um design muito intuitivo e divertido.",
  "Oportunidades": "Expansão para programas de saúde mental e educação financeira, parcerias com planos de saúde, integração com sistemas de benefícios da empresa.",
  "Ameaças": "Concorrência de outras plataformas de bem-estar corporativo, dificuldade de provar o retorno sobre o investimento (ROI) para as empresas, ceticismo dos funcionários.",
  "Resumo": "WellPlay Corporativo é a plataforma de gamificação que transforma o bem-estar em uma jornada divertida e competitiva, promovendo hábitos saudáveis e aumentando a produtividade e a satisfação no ambiente de trabalho.",
  "Área de Atuação": "Bem-estar corporativo, gamificação, saúde, RH, tecnologia.",
  "Nível de Experiência": "Intermediário a Avançado",
  "Recursos Disponíveis": "Equipe de desenvolvedores, designers de jogos, especialistas em saúde e RH, plataforma de gerenciamento de recompensas.",
  "Prazo Desejado": "9 meses para o lançamento do MVP e validação com uma empresa-piloto.",
  "Preço Inicial": "Modelo de assinatura para empresas, com preço baseado no número de funcionários.",
  "Receitas": "Assinaturas de empresas, venda de recompensas personalizadas, consultoria para implementação do programa.",
  "Critério de Sucesso": "Alto engajamento dos funcionários, feedback positivo do RH e do C-level, e impacto mensurável na saúde e produtividade da empresa."
},
"Hortas Terapêuticas e Comunidade Online":
{
  "nomeDoProjeto": "Jardim da Mente",
  "Objetivo Principal": "Combinar a jardinagem urbana com uma plataforma online para criar uma comunidade de apoio e bem-estar mental.",
  "Problema": "Muitas pessoas urbanas sofrem de estresse e falta de conexão com a natureza, e buscam alternativas para o bem-estar que sejam práticas e comunitárias.",
  "Solução": "Um projeto que oferece espaços de hortas urbanas para a comunidade e, em paralelo, uma plataforma digital para que os participantes compartilhem experiências, dicas e se apoiem em sua jornada de jardinagem e saúde mental.",
  "Solução Proposta": "Desenvolver um programa de hortas comunitárias e uma plataforma online que conecta os jardineiros, oferecendo tutoriais de jardinagem, sessões de meditação guiada e grupos de apoio moderados.",
  "Público/Segmentos": "Moradores de grandes cidades, entusiastas de jardinagem, pessoas que buscam terapias alternativas, terapeutas e psicólogos, empresas com foco em bem-estar de funcionários.",
  "Canais": "Parcerias com condomínios e prefeituras, redes sociais com foco em jardinagem e saúde mental, centros comunitários e feiras de bairro.",
  "MVP": "Um espaço de horta comunitária em um bairro-piloto e um grupo no WhatsApp para os participantes compartilharem fotos e dicas, com um moderador voluntário.",
  "Validação": "Monitoramento do engajamento no grupo online, coleta de feedback sobre os benefícios da jardinagem na saúde mental e o senso de comunidade criado.",
  "Critérios de Aceite": "Horta comunitária com 20 participantes ativos, 90% de engajamento no grupo online em 3 meses, relatos de melhoria no bem-estar mental dos participantes.",
  "OKRs": "O: Aumentar o bem-estar mental através da jardinagem; KR1: 80% dos participantes relatando menos estresse; KR2: 100% de ocupação dos canteiros da horta.",
  "Forças": "Aborda uma tendência crescente de busca por bem-estar e conexão com a natureza, cria um forte senso de comunidade, baixo custo inicial para o MVP.",
  "Fraquezas": "Dependência de espaço físico, desafios de manutenção e organização, dificuldade de escalar o modelo para outras cidades.",
  "Oportunidades": "Expansão para workshops e eventos de jardinagem terapêutica, parcerias com nutricionistas, vendas de produtos e sementes sustentáveis.",
  "Ameaças": "Desinteresse da comunidade, problemas climáticos que afetam as colheitas, concorrência de outras atividades de lazer em grupo.",
  "Resumo": "Jardim da Mente é uma iniciativa que une a terapia da jardinagem com o suporte de uma comunidade online, promovendo a saúde mental e a conexão com a natureza em ambientes urbanos.",
  "Área de Atuação": "Saúde mental, bem-estar, comunidade, jardinagem, sustentabilidade.",
  "Nível de Experiência": "Iniciante",
  "Recursos Disponíveis": "Terreno para a horta, ferramentas de jardinagem, voluntários para moderação, plataforma de comunicação (WhatsApp, Telegram).",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Preço Inicial": "Modelo freemium, com acesso gratuito à comunidade e hortas e uma assinatura para workshops e sementes premium.",
  "Receitas": "Assinaturas premium, vendas de produtos de jardinagem, doações, taxas de inscrição em workshops.",
  "Critério de Sucesso": "Comunidade online ativa, participantes relatando os benefícios da atividade e expansão do projeto para outros bairros."
},
"Círculos de Habilidades Locais":
{
  "nomeDoProjeto": "Habilidades na Vizinhanca",
  "Objetivo Principal": "Facilitar a troca de conhecimentos e habilidades entre vizinhos de um mesmo bairro ou comunidade.",
  "Problema": "Muitas pessoas têm habilidades valiosas (como costura, jardinagem ou aulas de idiomas) que poderiam ser ensinadas, enquanto outras querem aprender, mas não encontram um canal fácil e acessível de troca com a comunidade local.",
  "Solução": "A criação de um grupo online (via WhatsApp ou Telegram) com regras claras, onde os membros podem postar suas ofertas de 'aulas' e suas demandas, criando uma rede de troca de favores e saberes.",
  "Solução Proposta": "Lançar um grupo de comunicação para a comunidade, com um formulário simples (Google Forms) para o cadastro de habilidades e interesses, conectando os membros manualmente para as trocas.",
  "Público/Segmentos": "Moradores de bairros, aposentados, artesãos, estudantes, qualquer pessoa interessada em aprender ou ensinar sem custo.",
  "Canais": "Panfletos em centros comunitários, grupos de redes sociais de bairro, boca a boca entre os moradores.",
  "MVP": "Um grupo de WhatsApp com 30 vizinhos, com regras de convivência e um formulário online para cadastrar habilidades.",
  "Validação": "Acompanhamento do número de trocas de habilidades realizadas e feedback dos participantes sobre a utilidade e a facilidade de uso do grupo.",
  "Critérios de Aceite": "100 membros no grupo-piloto, 10 trocas de habilidades documentadas em 3 meses, feedback positivo da maioria dos participantes.",
  "OKRs": "O: Promover a troca de saberes na comunidade; KR1: 50% dos membros do grupo oferecendo uma habilidade; KR2: Atingir 20 trocas de conhecimento em 6 meses.",
  "Forças": "Custo zero, forte senso de comunidade, sustentabilidade, baixo risco, fácil de replicar em outros locais.",
  "Fraquezas": "Escalabilidade limitada, dependência do engajamento dos membros, desafios de moderação e segurança, não gera receita direta.",
  "Oportunidades": "Expansão para outros bairros, eventos presenciais (workshops), parcerias com pequenos negócios locais.",
  "Ameaças": "Desinteresse da comunidade, dificuldade de moderação, concorrência de plataformas online maiores.",
  "Resumo": "Habilidades na Vizinhanca é um projeto que usa a tecnologia mais simples para conectar vizinhos e promover a troca de conhecimentos, construindo uma comunidade mais forte e engajada de forma gratuita.",
  "Área de Atuação": "Comunidade, educação, economia da partilha.",
  "Nível de Experiência": "Iniciante",
  "Recursos Disponíveis": "Smartphone, aplicativo de mensagens (WhatsApp), Google Forms.",
  "Prazo Desejado": "3 meses para o lançamento e validação inicial.",
  "Preço Inicial": "Grátis.",
  "Receitas": "Nenhuma, o valor está na conexão e no impacto social.",
  "Critério de Sucesso": "Comunidade ativa, feedback positivo sobre as trocas de habilidades e o fortalecimento dos laços sociais."
},
"Banco de Horas Comunitário":
{
  "nomeDoProjeto": "Tempo em Troca",
  "Objetivo Principal": "Criar um sistema onde os membros de uma comunidade podem trocar tempo e favores sem a necessidade de dinheiro.",
  "Problema": "Muitas pessoas precisam de ajuda em tarefas do dia a dia (cuidar de um animal, fazer compras) mas não têm recursos financeiros, enquanto outras têm tempo disponível e desejam ajudar.",
  "Solução": "Um 'banco' onde o tempo é a moeda. Os participantes doam horas de trabalho para a comunidade, acumulando 'créditos de tempo' que podem ser usados para solicitar favores de outros membros.",
  "Solução Proposta": "Desenvolver um sistema baseado em uma planilha colaborativa (Google Sheets) onde os membros registram o tempo doado e solicitado, com um moderador comunitário para gerenciar o saldo e a troca de favores.",
  "Público/Segmentos": "Vizinhos, aposentados, estudantes, voluntários, qualquer pessoa disposta a ajudar e ser ajudada.",
  "Canais": "Centros comunitários, igrejas, grupos de bairro, boca a boca.",
  "MVP": "Uma planilha no Google Sheets com 50 membros, onde eles podem registrar as horas doadas (ex: 2h de jardinagem) e as horas recebidas (ex: 2h de cuidado com animais).",
  "Validação": "Análise da atividade na planilha, feedback dos participantes sobre a justiça e a praticidade do sistema e o número de favores trocados.",
  "Critérios de Aceite": "100 horas de trabalho doadas em 3 meses, 20 favores solicitados e realizados, feedback positivo sobre a utilidade do sistema.",
  "OKRs": "O: Fomentar o espírito de solidariedade na comunidade; KR1: 80% dos membros do banco realizando pelo menos um favor; KR2: Aumentar o saldo de horas doadas em 50% em 6 meses.",
  "Forças": "Custo zero, fortalece laços comunitários, incentiva a solidariedade, modelo de negócio sustentável e resiliente.",
  "Fraquezas": "Desafio de gerenciar a confiança, necessidade de um moderador ativo, dificuldade de escalar o projeto, dependência da boa vontade dos participantes.",
  "Oportunidades": "Integração com projetos de voluntariado, parcerias com ONGs, criação de um sistema de reputação para os membros.",
  "Ameaças": "Desequilíbrio entre oferta e demanda de favores, falta de engajamento, problemas de segurança entre os participantes.",
  "Resumo": "Tempo em Troca é um banco comunitário onde a moeda é o tempo, conectando vizinhos que precisam de ajuda com aqueles dispostos a doar seu tempo, fortalecendo a solidariedade local.",
  "Área de Atuação": "Comunidade, economia solidária, voluntariado, tecnologia cívica.",
  "Nível de Experiência": "Iniciante",
  "Recursos Disponíveis": "Google Sheets, internet, um moderador da comunidade.",
  "Prazo Desejado": "4 meses para o lançamento do MVP.",
  "Preço Inicial": "Grátis.",
  "Receitas": "Nenhuma, o valor está na conexão social.",
  "Critério de Sucesso": "Comunidade engajada, alto volume de trocas de favores e depoimentos positivos sobre o impacto do projeto."
},
"Mapa Colaborativo de Recursos Locais":
{
  "nomeDoProjeto": "Guia do Bairro",
  "Objetivo Principal": "Criar um mapa interativo e colaborativo com pontos de interesse e recursos úteis para a comunidade local.",
  "Problema": "Moradores, especialmente os novos, não conhecem os recursos do seu bairro, como pequenos produtores, feiras, pontos de coleta de lixo reciclável, áreas verdes e negócios locais.",
  "Solução": "Um mapa digital acessível e editável pela comunidade, onde cada morador pode adicionar e atualizar informações sobre recursos úteis, criando um guia vivo e dinâmico da região.",
  "Solução Proposta": "Utilizar a ferramenta de criação de mapas do Google Maps para que a comunidade possa marcar locais de interesse, como hortas urbanas, pequenos comércios e pontos de coleta de lixo, com informações e fotos.",
  "Público/Segmentos": "Moradores do bairro, recém-chegados, turistas, entusiastas de sustentabilidade, empreendedores locais.",
  "Canais": "Grupos de redes sociais de bairro, boca a boca, cartazes em murais de aviso, parceria com a administração do bairro.",
  "MVP": "Um mapa no Google Maps com a marcação de 10 pontos de interesse e o envio de um link editável para os primeiros 20 participantes.",
  "Validação": "Análise da quantidade de pontos adicionados ao mapa, feedback dos usuários sobre a utilidade do guia e o número de pessoas que acessam o mapa.",
  "Critérios de Aceite": "50 pontos de interesse mapeados em 3 meses, 80% de feedback positivo sobre a utilidade da ferramenta, 100 visualizações mensais no mapa.",
  "OKRs": "O: Mapear os recursos da comunidade; KR1: Mapear todos os pequenos produtores locais em 6 meses; KR2: Aumentar o número de pontos de interesse em 100% em um ano.",
  "Forças": "Custo zero de ferramenta, fácil de usar e editar, alto potencial de impacto social, promove a economia e o engajamento local.",
  "Fraquezas": "Desafio de moderação e verificação de informações, dependência de uma ferramenta externa (Google Maps), dificuldade de garantir que as informações estejam sempre atualizadas.",
  "Oportunidades": "Integração com outras plataformas comunitárias, expansão para o mapeamento de serviços (aulas, reparos), criação de um selo de 'verificado' para negócios locais.",
  "Ameaças": "Desinteresse da comunidade, vandalismo de informações no mapa, concorrência de plataformas de mapas maiores e mais genéricas.",
  "Resumo": "Guia do Bairro é um mapa colaborativo que une a comunidade para mapear e compartilhar os recursos locais, desde pequenos negócios a pontos de reciclagem, tornando o bairro mais conectado e sustentável.",
  "Área de Atuação": "Comunidade, sustentabilidade, tecnologia cívica, empreendedorismo.",
  "Nível de Experiência": "Iniciante",
  "Recursos Disponíveis": "Google Maps, internet, um coordenador comunitário.",
  "Prazo Desejado": "4 meses para o lançamento e validação do MVP.",
  "Preço Inicial": "Grátis.",
  "Receitas": "Nenhuma, o valor está na informação e no impacto social.",
  "Critério de Sucesso": "Mapa com informações ricas e atualizadas, alto volume de visualizações e feedback positivo sobre a sua utilidade para a comunidade."
},
"Plataforma de Inovação Aberta":
{
  "nomeDoProjeto": "InovaConnect",
  "Objetivo Principal": "Conectar grandes empresas e a academia com startups, empreendedores e talentos externos para resolver desafios de inovação.",
  "Problema": "Muitas grandes empresas têm dificuldade em inovar rapidamente, enquanto startups e talentos independentes não têm acesso aos desafios e recursos dessas empresas, limitando o potencial de crescimento de ambos.",
  "Solução": "Uma plataforma digital que centraliza desafios de inovação de empresas e permite que a comunidade de startups e especialistas submeta soluções. O sistema facilita a colaboração e a troca de conhecimento.",
  "Solução Proposta": "Desenvolver um portal web onde empresas podem postar 'desafios de inovação' e receber propostas de solução, com ferramentas para gerenciar projetos, fazer feedback e premiar as melhores ideias.",
  "Público/Segmentos": "Grandes empresas, startups, desenvolvedores, pesquisadores, universitários, investidores e freelancers.",
  "Canais": "Eventos de inovação, feiras de tecnologia, parcerias com universidades e aceleradoras, marketing digital focado em B2B.",
  "MVP": "Um site simples com três desafios de empresas parceiras, permitindo o cadastro de soluções e a comunicação direta entre os participantes e a empresa, com um processo de seleção manual.",
  "Validação": "Monitorar a quantidade e a qualidade das propostas recebidas para cada desafio e coletar feedback das empresas e dos participantes sobre a utilidade da plataforma.",
  "Critérios de Aceite": "100 propostas recebidas nos 3 primeiros desafios, 80% de satisfação dos parceiros empresariais e 2 soluções implementadas com sucesso.",
  "OKRs": "O: Fomentar a inovação aberta; KR1: 5 desafios de empresas postados mensalmente; KR2: 1 solução implementada por desafio em 6 meses.",
  "Forças": "Resolve um problema real de inovação para grandes empresas, potencial para gerar alto valor, cria um ecossistema de inovação.",
  "Fraquezas": "Desafio de atrair e engajar grandes empresas, necessidade de uma equipe de vendas e marketing B2B, alta concorrência no mercado de inovação.",
  "Oportunidades": "Expansão para outros setores, monetização através de taxas por desafio ou sucesso, criação de um banco de talentos e soluções pré-prontas.",
  "Ameaças": "Concorrência de outras plataformas de inovação, desinteresse de empresas em compartilhar desafios, desafios de segurança e propriedade intelectual.",
  "Resumo": "InovaConnect é a plataforma que conecta a necessidade de inovação de grandes empresas com a criatividade e a agilidade do ecossistema de startups, gerando soluções e oportunidades de negócio para todos.",
  "Área de Atuação": "Inovação, tecnologia, empreendedorismo, B2B.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Equipe de vendas B2B, desenvolvedores de plataforma web, especialistas em inovação e gestão de projetos.",
  "Prazo Desejado": "9 meses para o lançamento do MVP e a validação do modelo de negócio.",
  "Preço Inicial": "Modelo de assinatura para empresas que postam desafios, ou taxa de sucesso (success fee) sobre as soluções implementadas.",
  "Receitas": "Assinaturas de empresas, comissão sobre projetos e soluções implementadas, serviços de consultoria em inovação.",
  "Critério de Sucesso": "Implementação de soluções inovadoras, crescimento do número de empresas e participantes na plataforma e alta taxa de sucesso dos projetos."
},
"Rede de Colaboração para Startups Locais":
{
  "nomeDoProjeto": "Startup Hub Local",
  "Objetivo Principal": "Criar uma rede de apoio e colaboração para startups de uma mesma cidade, facilitando a troca de recursos, conhecimento e talentos.",
  "Problema": "Startups locais frequentemente operam de forma isolada, perdendo oportunidades de sinergia, acesso a talentos específicos e a conhecimentos sobre o mercado local.",
  "Solução": "Uma comunidade online (ex: Slack, Discord) e eventos presenciais que conectam fundadores, funcionários e mentores de startups, criando um ecossistema colaborativo e fortalecendo o crescimento local.",
  "Solução Proposta": "Desenvolver uma plataforma de comunicação ou usar uma já existente para conectar startups, organizar eventos e oferecer um banco de dados de recursos compartilháveis, como espaços de trabalho e serviços profissionais.",
  "Públicos/Segmentos": "Fundadores de startups, funcionários, mentores, investidores anjos, freelancers e estudantes de tecnologia.",
  "Canais": "Parcerias com hubs de inovação e universidades, eventos de networking, divulgação em redes sociais e blogs de tecnologia locais.",
  "MVP": "Um grupo no Slack ou Discord para 20 startups de uma mesma cidade, com canais para 'ajuda mútua', 'oferta de serviços' e 'eventos'.",
  "Validação": "Monitorar a atividade do grupo, o número de interações e a quantidade de parcerias e colaborações que surgiram por meio da rede.",
  "Critérios de Aceite": "100% de engajamento dos membros no grupo, 5 colaborações documentadas em 3 meses e 80% de satisfação com o valor da comunidade.",
  "OKRs": "O: Fortalecer o ecossistema local; KR1: 50 novas startups inscritas em 6 meses; KR2: Aumentar o número de parcerias entre startups em 25%.",
  "Forças": "Baixo custo inicial, alto potencial de impacto local, forte senso de comunidade, escalável para outras cidades.",
  "Fraquezas": "Dependência do engajamento dos membros, desafio de moderação e manutenção, concorrência com grupos mais genéricos.",
  "Oportunidades": "Monetização com serviços premium (ex: acesso a mentores), criação de um banco de talentos para startups, parcerias com fornecedores de serviços B2B.",
  "Ameaças": "Dispersão de membros em outras plataformas, falta de interesse da comunidade, falhas na moderação que prejudiquem o ambiente.",
  "Resumo": "Startup Hub Local é a rede que une o ecossistema de startups de uma cidade, fomentando a colaboração, o compartilhamento de recursos e o crescimento coletivo para impulsionar a economia local.",
  "Área de Atuação": "Empreendedorismo, tecnologia, comunidade, inovação.",
  "Nível de Experiência": "Iniciante",
  "Recursos Disponíveis": "Plataforma de comunicação (Slack), voluntários, parcerias locais.",
  "Prazo Desejado": "4 meses para o lançamento e validação do MVP.",
  "Preço Inicial": "Grátis, com possibilidade de um modelo de receita futuro.",
  "Receitas": "Taxas de eventos e workshops, assinaturas para serviços premium.",
  "Critério de Sucesso": "Comunidade ativa, alta taxa de colaboração entre startups e crescimento sustentável da rede."
},
"Marketplace de APIs Locais":
{
  "nomeDoProjeto": "API Cidades",
  "Objetivo Principal": "Oferecer um marketplace que centraliza e disponibiliza APIs de dados e serviços locais para desenvolvedores e startups.",
  "Problema": "O acesso a dados locais (como transporte, eventos, dados ambientais) é fragmentado e difícil. Desenvolvedores perdem tempo procurando e integrando APIs que poderiam ser padronizadas em um só lugar.",
  "Solução": "Um marketplace que organiza e padroniza APIs de dados locais, permitindo que desenvolvedores as encontrem facilmente, e que provedores de dados as vendam de forma segura e eficiente.",
  "Solução Proposta": "Desenvolver uma plataforma para listar e gerenciar APIs, com documentação clara, SDKs para as linguagens mais usadas e um sistema de pagamento para acesso a APIs premium.",
  "Públicos/Segmentos": "Desenvolvedores, startups de tecnologia, prefeituras, empresas de dados, pesquisadores, urbanistas.",
  "Canais": "Comunidades de desenvolvedores, hackathons, eventos de tecnologia e dados abertos, marketing B2B para prefeituras e empresas.",
  "MVP": "Um site com 5 APIs de dados públicos de uma cidade (ex: trânsito e transporte), com documentação básica para integração.",
  "Validação": "Monitorar o número de acessos e a taxa de uso das APIs, coletar feedback de desenvolvedores sobre a usabilidade da plataforma e a qualidade da documentação.",
  "Critérios de Aceite": "100 desenvolvedores usando as APIs em 3 meses, 80% de satisfação com a documentação e 5 projetos de desenvolvedores que usaram as APIs publicamente.",
  "OKRs": "O: Criar uma base de dados local; KR1: 50 APIs de dados locais cadastradas em 6 meses; KR2: Atingir 1.000 usuários ativos na plataforma.",
  "Forças": "Atende a uma necessidade técnica específica, grande potencial para B2B e B2G, cria uma base de dados valiosa para a economia local.",
  "Fraquezas": "Desafio de conseguir acesso aos dados de prefeituras e empresas, complexidade técnica do desenvolvimento da plataforma, necessidade de garantir a segurança dos dados.",
  "Oportunidades": "Expansão para outras cidades, criação de uma API de pagamento para micro-transações, serviços de consultoria para integração.",
  "Ameaças": "Grandes empresas que já oferecem APIs similares, problemas de segurança e privacidade de dados, dificuldade de regulamentação.",
  "Resumo": "API Cidades é o marketplace de APIs locais que descomplica o acesso a dados e serviços urbanos, permitindo que desenvolvedores criem soluções mais inovadoras para a cidade.",
  "Área de Atuação": "Tecnologia, desenvolvimento, governo, urbanismo, inovação.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Desenvolvedores de API e plataforma, especialistas em dados, parcerias com prefeituras.",
  "Prazo Desejado": "12 meses para o lançamento do MVP e a validação inicial.",
  "Preço Inicial": "Modelo freemium, com APIs públicas gratuitas e APIs premium de empresas pagas por acesso ou assinatura.",
  "Receitas": "Assinaturas para APIs premium, comissão sobre transações, taxas de serviço para provedores de API.",
  "Critério de Sucesso": "Crescimento da base de desenvolvedores, aumento do número de APIs disponíveis e implementação de projetos inovadores que usam a plataforma."
},
"Plataforma de Crowdsourcing de Ideias":
{
  "nomeDoProjeto": "IdeiaLab",
  "Objetivo Principal": "Oferecer uma plataforma para empresas, organizações e comunidades coletarem, avaliarem e selecionarem ideias de um público amplo e diverso.",
  "Problema": "Empresas e organizações muitas vezes buscam novas ideias e insights, mas não têm um canal organizado para isso, perdendo a oportunidade de aproveitar a inteligência coletiva de seu público.",
  "Solução": "Uma plataforma que cria um canal estruturado de crowdsourcing, onde os usuários podem submeter ideias em resposta a desafios específicos, votar nas melhores propostas e interagir para melhorá-las.",
  "Solução Proposta": "Desenvolver um software que permite a criação de 'campanhas de ideias' com prazos definidos, um sistema de submissão e votação, e ferramentas de moderação para gerenciar o processo de forma eficiente.",
  "Público/Segmentos": "Empresas, ONGs, órgãos governamentais, comunidades, funcionários de empresas, clientes e público em geral.",
  "Canais": "Marketing B2B para empresas, parcerias com ONGs, divulgação em mídias sociais e blogs de inovação.",
  "MVP": "Um site com uma campanha de ideia ativa, onde os usuários podem submeter ideias e votar com um 'curtir'. O processo de avaliação é manual.",
  "Validação": "Analisar o número de ideias submetidas, o engajamento dos usuários (curtidas e comentários) e coletar feedback das organizações sobre a qualidade das propostas.",
  "Critérios de Aceite": "100 ideias submetidas na primeira campanha, 80% de satisfação da organização com a ferramenta e 2 ideias selecionadas para a próxima etapa.",
  "OKRs": "O: Coletar insights valiosos; KR1: 5 campanhas de crowdsourcing lançadas em 6 meses; KR2: Atingir 1.000 usuários ativos na plataforma.",
  "Forças": "Baixo custo para a organização obter novas ideias, potencial para engajar a comunidade, solução ágil para problemas de inovação.",
  "Fraquezas": "Desafio de moderação de ideias, risco de receber propostas de baixa qualidade, necessidade de um design muito intuitivo.",
  "Oportunidades": "Expansão para uso interno em empresas, monetização com taxas por campanha, integração com outras ferramentas de gestão de projetos.",
  "Ameaças": "Desinteresse da comunidade, concorrência de plataformas mais genéricas (como redes sociais), desafios de propriedade intelectual sobre as ideias submetidas.",
  "Resumo": "IdeiaLab é a plataforma de crowdsourcing que conecta empresas e organizações com a inteligência coletiva de sua comunidade, facilitando a coleta de ideias inovadoras e valiosas para a resolução de desafios.",
  "Área de Atuação": "Inovação, gestão, comunidade, tecnologia, crowdsourcing.",
  "Nível de Experiência": "Intermediário",
  "Recursos Disponíveis": "Desenvolvedores de plataforma web, especialistas em inovação e moderação de comunidades.",
  "Prazo Desejado": "6 meses para o lançamento do MVP e a validação inicial.",
  "Preço Inicial": "Modelo de taxa por campanha ou assinatura mensal para empresas.",
  "Receitas": "Taxas de campanha, assinaturas para empresas, serviços de consultoria para a gestão de ideias.",
  "Critério de Sucesso": "Alto volume de ideias submetidas, engajamento ativo da comunidade e implementação de ideias valiosas nas organizações que usam a plataforma."
},
};
